## 1.Making Unit Vectors

### 1-1.두개의 벡터

In [1]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)

# generate test vectors
n_element = 4
u = np.random.uniform(0, 10, (n_element, ))
v = np.random.uniform(0, 10, (n_element, ))
print(f'u: {u}, shape: {u.shape}')
print(f'v: {v}, shape: {v.shape}\n')

# calculate and print the norms before unitization
u_norm = np.sqrt(np.sum(np.square(u)))
v_norm = np.sqrt(np.sum(np.square(v)))
print(colored('Before unitization', 'green'))
print(f'u_norm: {u_norm.round(2)}, v_norm: {v_norm.round(2)}\n')

# unitize the vectors
u = u/u_norm
v = v/v_norm

# calculate and print the norms after unitization
u_norm = np.sqrt(np.sum(np.square(u)))
v_norm = np.sqrt(np.sum(np.square(v)))
print(colored('After unitization', 'green'))
print(f'u_norm: {u_norm.round(2)}, v_norm: {v_norm.round(2)}')

u: [2.76 0.67 3.91 2.45], shape: (4,)
v: [4.37 3.5  2.92 8.39], shape: (4,)

Before unitization
u_norm: 5.42, v_norm: 10.51

After unitization
u_norm: 1.0, v_norm: 1.0


### 1-2.여러 벡터가 행렬 형태로 있을때

In [2]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)

# generate test vectors
n_vector, n_element = 3,4
U = np.random.uniform(0, 10, (n_vector, n_element))
print(f'U:\n{U}, shape: {U.shape}\n')

# calculate and print the norms before unitization
norms = np.sqrt(np.sum(np.square(U), axis=1, keepdims=True))
print(colored('Before unitization', 'green'))
print(f'norms:\n{norms}, shape: {norms.shape}\n')

# unitize the vectors
U = U/norms

# calculate and print the norms after unitization
norms = np.sqrt(np.sum(np.square(U), axis=1, keepdims=True))
print(colored('After unitization', 'green'))
print(f'norms:\n{norms}, shape: {norms.shape}')

U:
[[8.88 4.58 0.96 5.03]
 [2.53 9.44 4.54 5.16]
 [5.24 7.05 6.16 8.64]], shape: (3, 4)

Before unitization
norms:
[[11.23]
 [11.95]
 [13.78]], shape: (3, 1)

After unitization
norms:
[[1.]
 [1.]
 [1.]], shape: (3, 1)


## 2.Euclidean Distance

### 2-1.두개의 벡터

In [3]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_element = 4
u = np.random.uniform(0, 10, (n_element, ))
v = np.random.uniform(0, 10, (n_element, ))
print(f'u: {u}, shape: {u.shape}')
print(f'v: {v}, shape: {v.shape}\n')

# calculate and print the Euclidean distance
e_distance = np.sqrt(np.sum(np.square(u-v)))
print(f'Euclidean distance: {e_distance.round(2)}')

u: [5.87 8.33 8.51 0.06], shape: (4,)
v: [9.14 8.75 6.52 2.72], shape: (4,)

Euclidean distance: 4.68


### 2-2.Vector-wise

In [4]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector, n_element = 3,4
U = np.random.uniform(0, 10, (n_vector, n_element))
V = np.random.uniform(0, 10, (n_vector, n_element))
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# calculate and print the Euclidean distance
e_distance = np.sqrt(np.sum(np.square(U-V), axis=1))
print(f'Euclidean distances:\n{e_distance}, shape: {e_distance.shape}')

U:
[[8.07 3.65 0.65 4.46]
 [3.24 9.72 1.9  7.87]
 [9.91 3.04 7.36 2.58]], shape: (3, 4)
V:
[[5.96 8.32 9.66 5.72]
 [8.53 7.33 5.59 7.08]
 [7.09 8.42 1.29 6.21]], shape: (3, 4)

Euclidean distances:
[10.45  6.92  9.32], shape: (3,)


### 2-3.Fully-connected

In [5]:
import numpy as np
from termcolor import colored
np.set_printoptions(precision=2)

# generate test vectors
n_vector1, n_vector2 = 3,4
n_element = 4
U = np.random.uniform(0, 10, (n_vector1, n_element))
V = np.random.uniform(0, 10, (n_vector2, n_element))
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# reshape matrix
print(colored('After reshape', 'green'))
U = np.expand_dims(U, axis=1)
V = np.expand_dims(V, axis=0)
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# calculate and print the Euclidean distance
e_distance = np.sqrt(np.sum(np.square(U - V), axis=-1))
print(f'Euclidean distances:\n{e_distance}, shape: {e_distance.shape}')

U:
[[3.99e+00 6.34e+00 1.62e+00 4.35e+00]
 [7.01e+00 4.28e+00 9.81e-01 6.75e-01]
 [1.96e-03 9.63e+00 8.88e+00 3.26e+00]], shape: (3, 4)
V:
[[1.43 2.37 1.   1.39]
 [7.03 4.8  8.84 2.23]
 [3.48 8.15 4.42 8.31]
 [8.41 9.31 0.25 5.97]], shape: (4, 4)

After reshape
U:
[[[3.99e+00 6.34e+00 1.62e+00 4.35e+00]]

 [[7.01e+00 4.28e+00 9.81e-01 6.75e-01]]

 [[1.96e-03 9.63e+00 8.88e+00 3.26e+00]]], shape: (3, 1, 4)
V:
[[[1.43 2.37 1.   1.39]
  [7.03 4.8  8.84 2.23]
  [3.48 8.15 4.42 8.31]
  [8.41 9.31 0.25 5.97]]], shape: (1, 4, 4)

Euclidean distances:
[[ 5.61  8.26  5.21  5.73]
 [ 5.95  8.02  9.88  7.47]
 [10.97  8.59  7.72 12.36]], shape: (3, 4)


## 3.Manhattan Distance

### 3-1.두개의 벡터

In [6]:
import numpy as np

# generate test vectors
n_element = 4
u = np.random.randint(0, 10, (n_element, ))
v = np.random.randint(0, 10, (n_element, ))
print(f'u: {u}, shape')
print(f'v: {v}\n')

# calculate and print tne Manhattan distance
m_distance = np.sum(np.abs(u - v))
print(f'Manhattan distance: {m_distance}')

u: [4 0 6 7], shape
v: [7 0 1 5]

Manhattan distance: 10


### 3-2.Vector-wise

In [7]:
import numpy as np

# generate test vectors
n_vector, n_element = 3,4
U = np.random.randint(0, 10, (n_vector, n_element))
V = np.random.randint(0, 10, (n_vector, n_element))
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# calculate and print tne Manhattan distance
m_distances = np.sum(np.abs(U - V), axis=1)
print(f'Manhattan distances:\n{m_distances}, shape: {m_distances.shape}')

U:
[[0 0 3 5]
 [3 5 1 0]
 [5 4 6 4]], shape: (3, 4)
V:
[[6 4 5 7]
 [7 6 2 0]
 [0 8 1 0]], shape: (3, 4)

Manhattan distances:
[14  6 18], shape: (3,)


### 3-3.Fully-connected

In [8]:
import numpy as np
from termcolor import colored

# generate test vectors
n_vector1, n_vector2 = 3,4
n_element = 4
U = np.random.randint(0, 10, (n_vector1, n_element))
V = np.random.randint(0, 10, (n_vector2, n_element))
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# reshape matrix
print(colored('After reshape', 'green'))
U = np.expand_dims(U, axis=1)
V = np.expand_dims(V, axis=0)
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# calculate and print tne Manhattan distance
m_distances = np.sum(np.abs(U - V), axis=-1)
print(f'Manhattan distances:\n{m_distances}, shape: {m_distances.shape}')

U:
[[1 0 2 6]
 [2 7 2 8]
 [6 0 5 0]], shape: (3, 4)
V:
[[9 2 4 9]
 [6 6 5 0]
 [5 4 8 4]
 [1 3 2 0]], shape: (4, 4)

After reshape
U:
[[[1 0 2 6]]

 [[2 7 2 8]]

 [[6 0 5 0]]], shape: (3, 1, 4)
V:
[[[9 2 4 9]
  [6 6 5 0]
  [5 4 8 4]
  [1 3 2 0]]], shape: (1, 4, 4)

Manhattan distances:
[[15 20 16  9]
 [15 16 16 13]
 [15  6 12 11]], shape: (3, 4)


## 4.Cosine Similarity

### 4-1.두개의 벡터

In [9]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_element = 4
u = np.random.uniform(0, 10, (n_element, ))
v = np.random.uniform(0, 10, (n_element, ))
print(f'u: {u}, shape: {u.shape}')
print(f'v: {v}, shape: {v.shape}\n')

# calculate norm and unitize vector
u_norm = np.sqrt(np.sum(np.square(u)))
u_unit = u/u_norm
v_norm = np.sqrt(np.sum(np.square(v)))
v_unit = v/v_norm
print(f'u_unit: {u_unit}, shape: {u_unit.shape}')
print(f'v_unit: {v_unit}, shape: {v_unit.shape}\n')

# calculate and print norms of unit vectors
u_unit_norm = np.sqrt(np.sum(np.square(u_unit)))
v_unit_norm = np.sqrt(np.sum(np.square(v_unit)))
print(f'u_unit_norm: {u_unit_norm.round(2)}, v_unit_norm: {v_unit_norm.round(2)}\n')

# dot product
dot = np.sum(u_unit * v_unit)
print(f'dot product: {dot.round(2)}')
cos = dot # 단위 벡터로 바꾸어 주었기때문
print(f'cosine value: {cos.round(2)}')

u: [6.21 1.71 5.73 2.67], shape: (4,)
v: [1.15 9.48 5.4  4.48], shape: (4,)

u_unit: [0.69 0.19 0.63 0.3 ], shape: (4,)
v_unit: [0.1  0.8  0.46 0.38], shape: (4,)

u_unit_norm: 1.0, v_unit_norm: 1.0

dot product: 0.62
cosine value: 0.62


### 4-2.Vector-wise

In [10]:
import numpy as np
np.set_printoptions(precision=2)

# generate test vectors
n_vector, n_element = 3,4
U = np.random.randint(0, 10, (n_vector, n_element))
V = np.random.randint(0, 10, (n_vector, n_element))
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# calculate norm and unitize vector
U_norms = np.sqrt(np.sum(np.square(U), axis=1, keepdims=True))
V_norms = np.sqrt(np.sum(np.square(V), axis=1, keepdims=True))
U_unit = U / U_norms
V_unit = V / V_norms
print(f'U_unit:\n{U_unit}, shape: {U_unit.shape}')
print(f'V_unit:\n{V_unit}, shape: {V_unit.shape}\n')

# calculate and print norms of unit vectors
U_unit_norms = np.sqrt(np.sum(np.square(U_unit), axis=1, keepdims=True))
V_unit_norms = np.sqrt(np.sum(np.square(V_unit), axis=1, keepdims=True))
print(f'U_unit_norm:\n{U_unit_norms}')
print(f'V_unit_norm:\n{V_unit_norms}\n')

# calculate cos similartities
sims = np.sum(U_unit*V_unit, axis=1)
print(f'cos similartities: {sims}, shape: {sims.shape}')

U:
[[1 1 5 6]
 [6 4 4 5]
 [5 8 4 8]], shape: (3, 4)
V:
[[0 0 1 6]
 [9 8 7 0]
 [4 9 8 5]], shape: (3, 4)

U_unit:
[[0.13 0.13 0.63 0.76]
 [0.62 0.41 0.41 0.52]
 [0.38 0.62 0.31 0.62]], shape: (3, 4)
V_unit:
[[0.   0.   0.16 0.99]
 [0.65 0.57 0.5  0.  ]
 [0.29 0.66 0.59 0.37]], shape: (3, 4)

U_unit_norm:
[[1.]
 [1.]
 [1.]]
V_unit_norm:
[[1.]
 [1.]
 [1.]]

cos similartities: [0.85 0.85 0.93], shape: (3,)


### 4-3.Fully-connected

In [11]:
import numpy as np
from termcolor import colored

# generate test vectors
n_vector1, n_vector2 = 3,4
n_element = 4
U = np.random.uniform(0, 10, (n_vector1, n_element))
V = np.random.uniform(0, 10, (n_vector2, n_element))
print(f'U:\n{U}, shape: {U.shape}')
print(f'V:\n{V}, shape: {V.shape}\n')

# calculate norm and unitize vector
U_norms = np.sqrt(np.sum(np.square(U), axis=1, keepdims=True))
V_norms = np.sqrt(np.sum(np.square(V), axis=1, keepdims=True))
U_unit = U / U_norms
V_unit = V / V_norms
print(f'U_unit:\n{U_unit}, shape: {U_unit.shape}')
print(f'V_unit:\n{V_unit}, shape: {V_unit.shape}\n')

# calculate and print norms of unit vectors
U_unit_norms = np.sqrt(np.sum(np.square(U_unit), axis=1, keepdims=True))
V_unit_norms = np.sqrt(np.sum(np.square(V_unit), axis=1, keepdims=True))
print(f'U_unit_norm:\n{U_unit_norms}')
print(f'V_unit_norm:\n{V_unit_norms}\n')

# reshape matrix
print(colored('After reshape', 'green'))
U_unit = np.expand_dims(U_unit, axis=1)
V_unit = np.expand_dims(V_unit, axis=0)
print(f'U_unit:\n{U_unit}, shape: {U_unit.shape}')
print(f'V_unit:\n{V_unit}, shape: {V_unit.shape}\n')

# calculate cos similartities
sims = np.sum(U_unit* V_unit, axis=-1)
print(f'cos similartities:\n{sims}, shape:{sims.shape}')

U:
[[9.21 1.37 1.9  8.73]
 [1.17 8.39 2.84 1.69]
 [8.73 0.41 5.18 9.6 ]], shape: (3, 4)
V:
[[2.96 5.59 6.96 1.13]
 [7.55 5.08 2.23 2.84]
 [8.35 1.48 9.87 9.3 ]
 [4.82 6.98 6.49 9.82]], shape: (4, 4)

U_unit:
[[0.71 0.11 0.15 0.68]
 [0.13 0.92 0.31 0.19]
 [0.62 0.03 0.37 0.69]], shape: (3, 4)
V_unit:
[[0.31 0.59 0.74 0.12]
 [0.77 0.52 0.23 0.29]
 [0.52 0.09 0.62 0.58]
 [0.33 0.48 0.45 0.68]], shape: (4, 4)

U_unit_norm:
[[1.]
 [1.]
 [1.]]
V_unit_norm:
[[1.]
 [1.]
 [1.]
 [1.]]

After reshape
U_unit:
[[[0.71 0.11 0.15 0.68]]

 [[0.13 0.92 0.31 0.19]]

 [[0.62 0.03 0.37 0.69]]], shape: (3, 1, 4)
V_unit:
[[[0.31 0.59 0.74 0.12]
  [0.77 0.52 0.23 0.29]
  [0.52 0.09 0.62 0.58]
  [0.33 0.48 0.45 0.68]]], shape: (1, 4, 4)

cos similartities:
[[0.47 0.84 0.87 0.81]
 [0.84 0.7  0.45 0.75]
 [0.57 0.78 0.96 0.85]], shape:(3, 4)
