## 1.Shuffling a Vector

In [1]:
import numpy as np

a = np.arange(10)
print(a)

# shuffling
np.random.shuffle(a) # inplace function
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 2 4 8 3 7 6 1 9 0]


## 2.Shuffling a Matrix

In [2]:
import numpy as np

# shuffle by rows
M = np.arange(15).reshape(5, -1)
print(f"M:\n{M}\n")

np.random.shuffle(M) 
print(f"M:\n{M}\n")

# shuffle by cols
N = np.arange(15).reshape(5, -1)
print(f"N:\n{N}\n")

N = N.T
np.random.shuffle(N)
N = N.T
print(f"N:\n{N}")

M:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

M:
[[ 0  1  2]
 [12 13 14]
 [ 3  4  5]
 [ 9 10 11]
 [ 6  7  8]]

N:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

N:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## 3.shuffling Indices

In [3]:
import numpy as np
np.set_printoptions(precision=2)
from termcolor import colored

N = 10
a = np.linspace(0, 10, N)
b = np.linspace(0, 100, N)
print(colored('Before shuffling','green'))
print(f"a:\n{a}")
print(f"b:\n{b}\n")

# shuffling indices
indices = np.arange(N)
np.random.shuffle(indices)

a_shuffle = a[indices]
b_shuffle = b[indices]

print(colored('After shuffling','green'))
print(f"a:\n{a_shuffle}")
print(f"b:\n{b_shuffle}")

Before shuffling
a:
[ 0.    1.11  2.22  3.33  4.44  5.56  6.67  7.78  8.89 10.  ]
b:
[  0.    11.11  22.22  33.33  44.44  55.56  66.67  77.78  88.89 100.  ]

After shuffling
a:
[ 5.56  4.44 10.    1.11  7.78  8.89  3.33  6.67  0.    2.22]
b:
[ 55.56  44.44 100.    11.11  77.78  88.89  33.33  66.67   0.    22.22]


## 4.Shuffling X,Y Data

In [4]:
import numpy as np
from termcolor import colored

N, n_feature = 6, 5
n_class = 100

x_data = np.random.normal(0, 1, (N, n_feature))
y_data = np.random.randint(0, n_class, N)

print(colored('Before shuffling', 'green'))
print(f"x_data:\n{x_data}, shape: {x_data.shape}")
print(f"y_data:\n{y_data}, shape: {y_data.shape}\n")


# shuffling indices
indices = np.arange(N)
np.random.shuffle(indices)

x_data_shuffle = x_data[indices]
y_data_shuffle = y_data[indices]

print(colored('After shuffling', 'green'))
print(f"x_data_shuffle:\n{x_data_shuffle}, shape: {x_data_shuffle.shape}")
print(f"y_data_shuffle:\n{y_data_shuffle}, shape: {y_data_shuffle.shape}")

Before shuffling
x_data:
[[-0.01 -0.08 -1.46 -0.44 -1.17]
 [ 0.68  0.73  0.45 -0.04  1.53]
 [ 0.96  0.92 -0.78  0.22 -0.09]
 [-0.34  1.47 -1.34 -0.08  0.21]
 [ 1.56  0.39  2.05 -0.56  0.93]
 [ 1.01  1.43  1.32 -0.77 -0.44]], shape: (6, 5)
y_data:
[68 86 33 74  0 23], shape: (6,)

After shuffling
x_data_shuffle:
[[ 0.96  0.92 -0.78  0.22 -0.09]
 [-0.01 -0.08 -1.46 -0.44 -1.17]
 [ 0.68  0.73  0.45 -0.04  1.53]
 [-0.34  1.47 -1.34 -0.08  0.21]
 [ 1.01  1.43  1.32 -0.77 -0.44]
 [ 1.56  0.39  2.05 -0.56  0.93]], shape: (6, 5)
y_data_shuffle:
[33 68 86 74 23  0], shape: (6,)


## 5.Shuffling and Getting Minibatches

In [5]:
import numpy as np

N, n_feature = 200, 5
n_class = 100
batch_size = 32
iters = 8

x_data = np.random.normal(0, 1, (N, n_feature))
y_data = np.random.randint(0, n_class, N)

# 데이터가 중복될수도 있게 뽑기
for iter in range(iters):
    indices = np.arange(N)
    np.random.shuffle(indices)
    batch_indices = indices[:batch_size]

    x_batch = x_data[batch_indices]
    y_batch = y_data[batch_indices]
    
    print(f"iter: {iter+1}")
    print(f"X/Y: {x_batch.shape}/{y_batch.shape}")

iter: 1
X/Y: (32, 5)/(32,)
iter: 2
X/Y: (32, 5)/(32,)
iter: 3
X/Y: (32, 5)/(32,)
iter: 4
X/Y: (32, 5)/(32,)
iter: 5
X/Y: (32, 5)/(32,)
iter: 6
X/Y: (32, 5)/(32,)
iter: 7
X/Y: (32, 5)/(32,)
iter: 8
X/Y: (32, 5)/(32,)


In [6]:
import numpy as np

N, n_feature = 200, 5
n_class = 100
batch_size = 32
iters = 8

x_data = np.random.normal(0, 1, (N, n_feature))
y_data = np.random.randint(0, n_class, N)

# 데이터 중복x -> 1epoch의 개념
indices = np.arange(N)
np.random.shuffle(indices)
for iter in range(iters):
    batch_indices = indices[iter*batch_size : (iter+1)*batch_size]

    if len(batch_indices) == 0:
        break

    x_batch = x_data[batch_indices]
    y_batch = y_data[batch_indices]
    
    print(f"iter: {iter+1}")
    print(f"X/Y: {x_batch.shape}/{y_batch.shape}")

iter: 1
X/Y: (32, 5)/(32,)
iter: 2
X/Y: (32, 5)/(32,)
iter: 3
X/Y: (32, 5)/(32,)
iter: 4
X/Y: (32, 5)/(32,)
iter: 5
X/Y: (32, 5)/(32,)
iter: 6
X/Y: (32, 5)/(32,)
iter: 7
X/Y: (8, 5)/(8,)
