## 1.One-hot Encoding/Decoding with One Sample

In [1]:
import numpy as np

n_class = 5
label = np.random.randint(0,n_class,1)
print(f"Before one-hot encoding: {label}\n")

# Encoding
label_enc = np.zeros(n_class, dtype=np.int)
label_enc[label] = 1
print(f"After one-hot encoding: {label_enc}\n")

# Decoding
## method 1
label = np.nonzero(label_enc)[0]
print(f"After one-hot decoding(method 1): {label}")

## method 2
label = np.where(label_enc == 1)[0]
print(f"After one-hot decoding(method 2): {label}")

## method 3
label = np.argmax(label_enc).flatten()
print(f"After one-hot decoding(method 3): {label}")

Before one-hot encoding: [1]

After one-hot encoding: [0 1 0 0 0]

After one-hot decoding(method 1): [1]
After one-hot decoding(method 2): [1]
After one-hot decoding(method 3): [1]


## 2.One-hot Encoding/Decoding with n Samples

In [2]:
import numpy as np

N, n_class = 10, 5

labels = np.random.randint(0, n_class, (N, ))
print(f"Before one-hot encoding: {labels}\n")

# Encoding
## method 1
labels_enc = np.zeros((N, n_class), dtype=np.int)
for idx, label in enumerate(labels):
    labels_enc[idx, label] = 1
print(f"After one-hot encoding(method 1):\n{labels_enc}")

## method 2
labels_enc = np.zeros((N, n_class), dtype=np.int)
labels_enc[np.arange(N), labels] = 1
print(f"After one-hot encoding(method 2):\n{labels_enc}\n")

# Decoding
## method 1
labels = np.zeros(N, dtype=np.int)
for idx, label_enc in enumerate(labels_enc):
    labels[idx] = np.argmax(label_enc)
print(f"After one-hot decoding(method 1): {labels}")

## method 2
labels = np.nonzero(labels_enc)[1]
print(f"After one-hot decoding(method 2): {labels}")

## method 3
labels = np.where(labels_enc == 1)[1]
print(f"After one-hot decoding(method 3): {labels}")

# method 4
labels = np.argmax(labels_enc, axis=1)
print(f"After one-hot decoding(method 4): {labels}")

Before one-hot encoding: [4 4 3 2 1 2 3 3 2 4]

After one-hot encoding(method 1):
[[0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
After one-hot encoding(method 2):
[[0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]

After one-hot decoding(method 1): [4 4 3 2 1 2 3 3 2 4]
After one-hot decoding(method 2): [4 4 3 2 1 2 3 3 2 4]
After one-hot decoding(method 3): [4 4 3 2 1 2 3 3 2 4]
After one-hot decoding(method 4): [4 4 3 2 1 2 3 3 2 4]
