## 1.Objects in Python
Object = Data + Methods

### 1-1.dir() Function
Object가 가지고 있는 method들을 리스트 형태로 반환

In [1]:
a = [1,2,3]
print('Methods of List:')
for atrr in dir(a):
    print(atrr)
print('\n')

b = {'a':1, 'b':2, 'c':3}
print('Methods of Dictionary:')
for atrr in dir(b):
    print(atrr)

Methods of List:
__add__
__class__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__imul__
__init__
__init_subclass__
__iter__
__le__
__len__
__lt__
__mul__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__reversed__
__rmul__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
append
clear
copy
count
extend
index
insert
pop
remove
reverse
sort


Methods of Dictionary:
__class__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__init__
__init_subclass__
__iter__
__le__
__len__
__lt__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
clear
copy
fromkeys
get
items
keys
pop
popitem
setdefault
update
values


### 1-2.type() Function
어떠한 class대한  Object인지를 반환

In [2]:
a = [1,2,3]
b = {'a':1, 'b':2, 'c':3}
c = (1,2,3)
print('Object type:')
print('[1,2,3] ->',type(a))
print('{"a":1, "b":2, "c":3} ->',type(b))
print('(1,2,3) ->',type(c))

Object type:
[1,2,3] -> <class 'list'>
{"a":1, "b":2, "c":3} -> <class 'dict'>
(1,2,3) -> <class 'tuple'>


## 2.Special Methods

### 2-1.Special Methods Examples

In [3]:
# --- Int Object
print('Int Object')
print('----------------------------------')
a, b = 5, 2
c = a + b
print('Object type:')
print('a = 10 ->',type(a))
print('b = 20 ->',type(b))
print('c = a + b ->',type(c),'\n')

print('print(a+b) = ',a+b)
print('print(a.__add__(b)) = ',a.__add__(b))
print('\n')
print('print(a-b) = ',a-b)
print('print(a.__sub__(b)) = ',a.__sub__(b))
print('\n')
print('print(a*b) = ',a*b)
print('print(a.__mul__(b)) = ',a.__mul__(b))
print('\n')
print('print(a**b) = ',a**b)
print('print(a.__pow__(b)) = ',a.__pow__(b))
print('\n')
print('print(a/b) = ',a/b)
print('print(a.__truediv__(b)) = ',a.__truediv__(b))
print('\n')
print('print(a//b) = ',a//b)
print('print(a.__floordiv__(b)) = ',a.__floordiv__(b))
print('\n')
print('print(a%b) = ',a%b)
print('print(a.__mod__(b)) = ',a.__mod__(b))
print('----------------------------------\n')
# ---

# --- List Object
print('List Object')
print('----------------------------------')
a = [1,2,3]
print('print(len(a)) = ',len(a))
print('print(a.__len__()) = ', a.__len__())
print('----------------------------------\n')

Int Object
----------------------------------
Object type:
a = 10 -> <class 'int'>
b = 20 -> <class 'int'>
c = a + b -> <class 'int'> 

print(a+b) =  7
print(a.__add__(b)) =  7


print(a-b) =  3
print(a.__sub__(b)) =  3


print(a*b) =  10
print(a.__mul__(b)) =  10


print(a**b) =  25
print(a.__pow__(b)) =  25


print(a/b) =  2.5
print(a.__truediv__(b)) =  2.5


print(a//b) =  2
print(a.__floordiv__(b)) =  2


print(a%b) =  1
print(a.__mod__(b)) =  1
----------------------------------

List Object
----------------------------------
print(len(a)) =  3
print(a.__len__()) =  3
----------------------------------



### 2-2.Different Special Methods in Different Objects

In [4]:
a,b = 10,20
print(f'a={a}, b={b}\na+b = {a+b}\na*b = {a*b}\n')

list1, list2 = [1,2,3], [4,5,6]
print(f'list1 = {list1}, list2 = {list2}\nlist1+list2 = {list1+list2}\n3*list1 = {3*list1}\n')

a=10, b=20
a+b = 30
a*b = 200

list1 = [1, 2, 3], list2 = [4, 5, 6]
list1+list2 = [1, 2, 3, 4, 5, 6]
3*list1 = [1, 2, 3, 1, 2, 3, 1, 2, 3]



## 3.ndarray Object of Numpy

### 3-1.Namespace and Import

In [5]:
import numpy as np

scores = [10, 20, 30, 40, 50]
print('mean:', np.mean(scores))
print('variance:', np.var(scores))

mean: 30.0
variance: 200.0


### 3-2.ndarray Objects

In [6]:
import numpy as np

a = np.array([1,2,3])
print('np.array([1,2,3]) type:',type(a),'\n')

print('Methods of ndarray:')
for atrr in dir(a):
    print(atrr)

np.array([1,2,3]) type: <class 'numpy.ndarray'> 

Methods of ndarray:
T
__abs__
__add__
__and__
__array__
__array_finalize__
__array_function__
__array_interface__
__array_prepare__
__array_priority__
__array_struct__
__array_ufunc__
__array_wrap__
__bool__
__class__
__complex__
__contains__
__copy__
__deepcopy__
__delattr__
__delitem__
__dir__
__divmod__
__doc__
__eq__
__float__
__floordiv__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__iand__
__ifloordiv__
__ilshift__
__imatmul__
__imod__
__imul__
__index__
__init__
__init_subclass__
__int__
__invert__
__ior__
__ipow__
__irshift__
__isub__
__iter__
__itruediv__
__ixor__
__le__
__len__
__lshift__
__lt__
__matmul__
__mod__
__mul__
__ne__
__neg__
__new__
__or__
__pos__
__pow__
__radd__
__rand__
__rdivmod__
__reduce__
__reduce_ex__
__repr__
__rfloordiv__
__rlshift__
__rmatmul__
__rmod__
__rmul__
__ror__
__rpow__
__rrshift__
__rshift__
__rsub__
__rtruediv__
__rxor__
__setattr__
__setitem__
__setstate__
__sizeof

### 3-3.Element-wise Operations of ndarrays

In [7]:
import numpy as np

u = np.array([1,2,3])
v = np.array([4,5,6])
print(f'{u} + {v} = {u+v}\n')

M = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
N = np.array([[11,12,13],
              [14,15,16],
              [17,18,19]])
print('M =')
print(M)
print('N =')
print(N)
print('M + N =')
print(M+N)

[1 2 3] + [4 5 6] = [5 7 9]

M =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
N =
[[11 12 13]
 [14 15 16]
 [17 18 19]]
M + N =
[[12 14 16]
 [18 20 22]
 [24 26 28]]
