## 1.np.reshape and ndarray.reshape


### 1-1.np.reshape(a, new_shape, order='C')

In [1]:
import numpy as np

# --- np.reshape(a, newshape, order='C')
a = np.arange(6)
b = np.reshape(a, (2,3))
print(f'original ndarray:\n{a}')
print(f'reshaped ndarray:\n{b}\n')

a = np.arange(24)
b = np.reshape(a, (2,3,4))
print(f'original ndarray:\n{a}')
print(f'reshaped ndarray:\n{b}\n')

original ndarray:
[0 1 2 3 4 5]
reshaped ndarray:
[[0 1 2]
 [3 4 5]]

original ndarray:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
reshaped ndarray:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



### 1-2.ndarray.reshape(shape, order='C')

In [2]:
import numpy as np

a = np.arange(6)
b = a.reshape((2,3))
print(f'original ndarray:\n{a}')
print(f'reshaped ndarray:\n{b}\n')

a = np.arange(24)
b = a.reshape((2,3,4))
print(f'original ndarray:\n{a}')
print(f'reshaped ndarray:\n{b}\n')

original ndarray:
[0 1 2 3 4 5]
reshaped ndarray:
[[0 1 2]
 [3 4 5]]

original ndarray:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
reshaped ndarray:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



### 1-3. the difference between np.reshape and ndarray.reshape

In [3]:
a = np.random.randint(0,100,(100,))

# np.reshape
print(np.max(np.mean(np.reshape(a,(20,5)), axis=0)))

# ndarray.reshape
print(a.reshape((20,5)).mean(axis=0).max())

50.6
50.6


### 1-4.-1 in np.reshape
나머지 차원의 값이 정해지면 남은 한차원의 고정된값을 자동적으로 연산

In [4]:
 a = np.arange(12)
 b = a.reshape((2,-1))
 c = a.reshape((3,-1))
 d = a.reshape((4,-1))
 e = a.reshape((6,-1))

print(f'original ndarray:\n{a}, shape = {a.shape}\n')
print(f'reshaped ndarray1:\n{b}, shape = {b.shape}\n')
print(f'reshaped ndarray2:\n{c}, shape = {c.shape}\n')
print(f'reshaped ndarray3:\n{d}, shape = {d.shape}\n')
print(f'reshaped ndarray4:\n{e}, shape = {e.shape}')

original ndarray:
[ 0  1  2  3  4  5  6  7  8  9 10 11], shape = (12,)

reshaped ndarray1:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]], shape = (2, 6)

reshaped ndarray2:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape = (3, 4)

reshaped ndarray3:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape = (4, 3)

reshaped ndarray4:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]], shape = (6, 2)


In [5]:
 a = np.arange(12)
 b = a.reshape((-1,2))
 c = a.reshape((-1,3))
 d = a.reshape((-1,4))
 e = a.reshape((-1,6))

print(f'original ndarray:\n{a}, shape = {a.shape}\n')
print(f'reshaped ndarray1:\n{b}, shape = {b.shape}\n')
print(f'reshaped ndarray2:\n{c}, shape = {c.shape}\n')
print(f'reshaped ndarray3:\n{d}, shape = {d.shape}\n')
print(f'reshaped ndarray4:\n{e}, shape = {e.shape}')

original ndarray:
[ 0  1  2  3  4  5  6  7  8  9 10 11], shape = (12,)

reshaped ndarray1:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]], shape = (6, 2)

reshaped ndarray2:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape = (4, 3)

reshaped ndarray3:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape = (3, 4)

reshaped ndarray4:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]], shape = (2, 6)


In [6]:
a = np.arange(24)
b = a.reshape((2,3,-1))
c = a.reshape((2,-1,4))
d = a.reshape((-1,3,4))

print(f'original ndarray:\n{a}, shape = {a.shape}\n')
print(f'reshaped ndarray1:\n{b}, shape = {b.shape}\n')
print(f'reshaped ndarray2:\n{c}, shape = {c.shape}\n')
print(f'reshaped ndarray3:\n{d}, shape = {d.shape}')

original ndarray:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape = (24,)

reshaped ndarray1:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape = (2, 3, 4)

reshaped ndarray2:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape = (2, 3, 4)

reshaped ndarray3:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape = (2, 3, 4)


In [7]:
a = np.random.randint(0,10,(2,2))
row_vector = a.reshape((1,-1))
col_vector = a.reshape((-1,1))

print(f'original ndarray:\n{a}, shape = {a.shape}\n')
print(f'reshaped ndarray1:\n{row_vector}, shape = {row_vector.shape}\n')
print(f'reshaped ndarray2:\n{col_vector}, shape = {col_vector.shape}')

original ndarray:
[[4 4]
 [7 4]], shape = (2, 2)

reshaped ndarray1:
[[4 4 7 4]], shape = (1, 4)

reshaped ndarray2:
[[4]
 [4]
 [7]
 [4]], shape = (4, 1)


## 2.np.resize and ndarray.resize

### 2-1.np.resize(a, new_shape)

In [8]:
import numpy as np

a = np.arange(6)
b = np.resize(a, (2,3))
print(f'original ndarray:\n{a}')
print(f'resized ndarray:\n{b}\n')

a = np.arange(6)
b = np.resize(a, (9,))
print(f'original ndarray:\n{a}')
print(f'resized ndarray:\n{b}\n')

a = np.arange(6)
b = np.resize(a, (4))
print(f'original ndarray:\n{a}')
print(f'resized ndarray:\n{b}\n')

a = np.arange(6)
b = np.resize(a, (3,4))
print(f'original ndarray:\n{a}')
print(f'resized ndarray:\n{b}\n')

a = np.arange(9)
b = np.resize(a, (2,3,3))
print(f'original ndarray:\n{a}')
print(f'resized ndarray:\n{b}\n')

a = np.arange(9)
b = np.resize(a, (2,2))
print(f'original ndarray:\n{a}')
print(f'resized ndarray:\n{b}')

original ndarray:
[0 1 2 3 4 5]
resized ndarray:
[[0 1 2]
 [3 4 5]]

original ndarray:
[0 1 2 3 4 5]
resized ndarray:
[0 1 2 3 4 5 0 1 2]

original ndarray:
[0 1 2 3 4 5]
resized ndarray:
[0 1 2 3]

original ndarray:
[0 1 2 3 4 5]
resized ndarray:
[[0 1 2 3]
 [4 5 0 1]
 [2 3 4 5]]

original ndarray:
[0 1 2 3 4 5 6 7 8]
resized ndarray:
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]

original ndarray:
[0 1 2 3 4 5 6 7 8]
resized ndarray:
[[0 1]
 [2 3]]


### 2-2.ndarray.resize(new_shape, refcheck=True)
Change shape and size of array in-place(그 자체의 값을 바꾸고 리턴을 하지않는다)

In [9]:
a = np.arange(8)
b = a.resize((2,2))
print(f'original ndarray:\n{a}')
print(f'resized ndarray:\n{b}\n')

a = np.arange(8)
print(f'original ndarray:\n{a}')
a.resize((2,2))
print(f'resized ndarray:\n{a}')

original ndarray:
[[0 1]
 [2 3]]
resized ndarray:
None

original ndarray:
[0 1 2 3 4 5 6 7]
resized ndarray:
[[0 1]
 [2 3]]


## 3.ndarray.flatten and ndarray.ravel

### 3-1.ndarray.flatten(order='C')

In [10]:
import numpy as np

M = np.arange(9)
N = M.reshape((3,-1))
O = N.flatten()

print(f'original ndarray:\n{M}')
print(f'resized ndarray:\n{N}')
print(f'flattened ndarray:\n{O}\n')

M = np.arange(27)
N = M.reshape((3,3,-1))
O = N.flatten()

print(f'original ndarray:\n{M}')
print(f'resized ndarray:\n{N}')
print(f'flattened ndarray:\n{O}')

original ndarray:
[0 1 2 3 4 5 6 7 8]
resized ndarray:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
flattened ndarray:
[0 1 2 3 4 5 6 7 8]

original ndarray:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
resized ndarray:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
flattened ndarray:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### 3-2.ndarray.ravel([order])

In [11]:
import numpy as np

M = np.arange(9)
N = M.reshape((3,-1))
O = N.ravel()

print(f'original ndarray:\n{M}')
print(f'resized ndarray:\n{N}')
print(f'flattened ndarray:\n{O}')

original ndarray:
[0 1 2 3 4 5 6 7 8]
resized ndarray:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
flattened ndarray:
[0 1 2 3 4 5 6 7 8]


## 4.Memory Optimization

### 4-1.view of ndarrays

In [12]:
import numpy as np

a = np.arange(5)
b = a.view()
print(f'b 수정전 a: {a}, b: {b}')
b[0] = 100
print(f'b 수정후 a: {a}, b: {b}\n')

a = np.arange(5)
b = a[0:3]
print(f'b 수정전 a: {a}, b: {b}')
b[...] = 10
print(f'b 수정후 a: {a}, b: {b}')

b 수정전 a: [0 1 2 3 4], b: [0 1 2 3 4]
b 수정후 a: [100   1   2   3   4], b: [100   1   2   3   4]

b 수정전 a: [0 1 2 3 4], b: [0 1 2]
b 수정후 a: [10 10 10  3  4], b: [10 10 10]


### 4-2.copy of ndarrays

In [13]:
import numpy as np

a = np.arange(5)
b = a.copy()
print(f'b 수정전 a: {a}, b: {b}')
b[0] = 100
print(f'b 수정후 a: {a}, b: {b}\n')

a = np.arange(5)
b = a[0:3].copy()
print(f'b 수정전 a: {a}, b: {b}')
b[...] = 10
print(f'b 수정후 a: {a}, b: {b}\n')

b 수정전 a: [0 1 2 3 4], b: [0 1 2 3 4]
b 수정후 a: [0 1 2 3 4], b: [100   1   2   3   4]

b 수정전 a: [0 1 2 3 4], b: [0 1 2]
b 수정후 a: [0 1 2 3 4], b: [10 10 10]



### 4-3. base of ndarrays

In [14]:
import numpy as np

a = np.arange(5)
b = a.copy()
c = a.view()
d = a[0:3]

print(b.base is a,'\n') # copy를 한것은 다른 메모리를 차지하기 때문에 원본 객체는 base가 아니다.

# --- view를 통해 만들어진 객체들의 base는 원본 객체이다.
print(c.base is a)
print(d.base is a)
# ---

False 

True
True


### 4-4.APIs and copy, view

In [15]:
# np.reshape

import numpy as np

a = np.arange(4)
b = np.reshape(a, (2,2))
print(f'b 수정전\na:\n{a}\nb:\n{b}\n')

print(f'b.base is a: {b.base is a}\n')

b[0][0] = 100
print(f'b 수정후\na:\n{a}\nb:\n{b}\n')
print('--------------------------------\n')

a = np.arange(4)
b = np.reshape(a, (2,2)).copy()
print(f'b 수정전\na:\n{a}\nb:\n{b}\n')

print(f'b.base is a: {b.base is a}\n')

b[0][0] = 100
print(f'b 수정후\na:\n{a}\nb:\n{b}')

b 수정전
a:
[0 1 2 3]
b:
[[0 1]
 [2 3]]

b.base is a: True

b 수정후
a:
[100   1   2   3]
b:
[[100   1]
 [  2   3]]

--------------------------------

b 수정전
a:
[0 1 2 3]
b:
[[0 1]
 [2 3]]

b.base is a: False

b 수정후
a:
[0 1 2 3]
b:
[[100   1]
 [  2   3]]


In [16]:
# np.resize

import numpy as np

a = np.arange(4)
b = np.resize(a, (2,2))
print(f'b 수정전\na:\n{a}\nb:\n{b}\n')

print(f'b.base is a: {b.base is a}\n')

b[0][0] = 100
print(f'b 수정후\na:\n{a}\nb:\n{b}\n')

b 수정전
a:
[0 1 2 3]
b:
[[0 1]
 [2 3]]

b.base is a: False

b 수정후
a:
[0 1 2 3]
b:
[[100   1]
 [  2   3]]



In [17]:
# ndarray.ravel

import numpy as np

a = np.random.randint(0,10,(2,3))
b = a.ravel()
print(f'b 수정전\na:\n{a}\nb:\n{b}\n')

print(f'b.base is a: {b.base is a}\n')

b[0] = 100

print(f'b 수정후\na:\n{a}\nb:\n{b}\n')

b 수정전
a:
[[4 1 5]
 [3 1 6]]
b:
[4 1 5 3 1 6]

b.base is a: True

b 수정후
a:
[[100   1   5]
 [  3   1   6]]
b:
[100   1   5   3   1   6]



In [18]:
# ndarray.flatten

import numpy as np

a = np.random.randint(0,10,(2,3))
b = a.flatten()
print(f'b 수정전\na:\n{a}\nb:\n{b}\n')

print(f'b.base is a: {b.base is a}\n')

b[0] = 100

print(f'b 수정후\na:\n{a}\nb:\n{b}\n')

b 수정전
a:
[[7 5 2]
 [1 7 8]]
b:
[7 5 2 1 7 8]

b.base is a: False

b 수정후
a:
[[7 5 2]
 [1 7 8]]
b:
[100   5   2   1   7   8]



## 5.ndarray.astype

### 5-1.ndarray.astpye

In [19]:
import numpy as np

M = np.array([1,2,3], dtype = np.int8)
print(f'Original data type: {M.dtype}')
N = M.astype(np.float32)
print(f'Changed data type: {N.dtype}')
O = M.astype(np.uint32)
print(f'Changed data type: {O.dtype}')

Original data type: int8
Changed data type: float32
Changed data type: uint32


In [20]:
import numpy as np

M = np.random.uniform(-10,10, (3,3))
print(f'M =\n{M}, dtype = {M.dtype}\n')

N = M.astype(np.int32)
print(f'N =\n{N}, dtype = {N.dtype}\n')

M =
[[ 5.64298533  2.7464384  -9.34807519]
 [-9.11067353 -0.39166072 -6.16094832]
 [-7.08603134  6.2057337   7.56398868]], dtype = float64

N =
[[ 5  2 -9]
 [-9  0 -6]
 [-7  6  7]], dtype = int32



### 5-2.bool dtype ndarrays 

In [21]:
import numpy as np

bools = np.array([True, False])
print(f'bool: \n{bools}')

bools2ints = bools.astype(np.int32)
print(f'int: \n{bools2ints}')

bools2floats = bools.astype(np.float32)
print(f'float: \n{bools2floats}\n')

# -------------------------------------------- #

ints = np.array([-2, -1, 0, 1, 2])
ints2bools = ints.astype(np.bool)
print(f'int:\n{ints}')
print(f'bool:\n{ints2bools}\n')

floats = np.array([-2.5, -1.5, 0., 1.5, 2.5])
floats2bools = floats.astype(np.bool)
print(f'float:\n{floats}')
print(f'bool:\n{floats2bools}')

bool: 
[ True False]
int: 
[1 0]
float: 
[1. 0.]

int:
[-2 -1  0  1  2]
bool:
[ True  True False  True  True]

float:
[-2.5 -1.5  0.   1.5  2.5]
bool:
[ True  True False  True  True]


In [22]:
print(f'-3 == True : {-3 == True}, -3 == False : {-3 == False}')
print(f'3.14 == True : {3.14 == True}, 3.14 == False : {3.14 == False}\n')

print(f'0. == True : {0. == True}, 0. == False : {0. == False}')
print(f'1. == True : {1. == True}, 1. == False : {1. == False}')

-3 == True : False, -3 == False : False
3.14 == True : False, 3.14 == False : False

0. == True : False, 0. == False : True
1. == True : True, 1. == False : False
