## 1. Element-wise Operations of ndarrays

### 1-1.Vector-vector Case

In [1]:
import numpy as np

a = np.random.randint(1, 5, (5, ))
b = np.random.randint(1, 5, (5, ))

print(f'a: {a}\nb: {b}\n')

print(f'a + b: {a + b}')
print(f'a - b: {a - b}')
print(f'a * b: {a * b}')
print(f'a / b: {a / b}')
print(f'a // b: {a // b}')
print(f'a % b: {a % b}')
print(f'a ** b: {a ** b}\n')

print(f'a > b: {a > b}')
print(f'a >= b: {a >= b}')
print(f'a < b: {a < b}')
print(f'a <= b: {a <= b}')
print(f'a == b: {a == b}')
print(f'a != b: {a != b}')

a: [2 4 3 3 4]
b: [2 4 3 3 4]

a + b: [4 8 6 6 8]
a - b: [0 0 0 0 0]
a * b: [ 4 16  9  9 16]
a / b: [1. 1. 1. 1. 1.]
a // b: [1 1 1 1 1]
a % b: [0 0 0 0 0]
a ** b: [  4 256  27  27 256]

a > b: [False False False False False]
a >= b: [ True  True  True  True  True]
a < b: [False False False False False]
a <= b: [ True  True  True  True  True]
a == b: [ True  True  True  True  True]
a != b: [False False False False False]


### 1-2.Matrix-Matrix Case

In [2]:
import numpy as np

M = np.random.randint(1, 5, (2,3))
N = np.random.randint(1, 5, (2,3))

print(f'M:\n{M}')
print(f'N:\n{N}\n')

print(f'M + N:\n{M+N}')
print(f'M - N:\n{M-N}')
print(f'M * N:\n{M*N}')
print(f'M / N:\n{M/N}\n')

print(f'M > N:\n{M > N}')
print(f'M < N:\n{M < N}')
print(f'M == N:\n{M == N}')
print(f'M != N:\n{M != N}')

M:
[[3 4 3]
 [4 4 2]]
N:
[[4 2 2]
 [3 1 2]]

M + N:
[[7 6 5]
 [7 5 4]]
M - N:
[[-1  2  1]
 [ 1  3  0]]
M * N:
[[12  8  6]
 [12  4  4]]
M / N:
[[0.75       2.         1.5       ]
 [1.33333333 4.         1.        ]]

M > N:
[[False  True  True]
 [ True  True False]]
M < N:
[[ True False False]
 [False False False]]
M == N:
[[False False False]
 [False False  True]]
M != N:
[[ True  True  True]
 [ True  True False]]


### 1-3.Element-wise Multiplication and Masking

In [3]:
import numpy as np

a = np.arange(5)
mask = np.array([0,1,0,1,0])
print(f'input: {a}')
print(f'mask: {mask}')
print(f'output: {a*mask}\n')

a = np.arange(1,5).reshape((2,2))
mask = np.array([[0,0],
                 [1,0]])
print(f'input:\n{a}')
print(f'mask:\n{mask}')
print(f'output:\n{a*mask}')

input: [0 1 2 3 4]
mask: [0 1 0 1 0]
output: [0 1 0 3 0]

input:
[[1 2]
 [3 4]]
mask:
[[0 0]
 [1 0]]
output:
[[0 0]
 [3 0]]


## 2.Broadcasting in Numpy

### 2-1.When ndims are equal

In [4]:
# --- Matrices
import numpy as np

M = np.arange(9).reshape((3,3))
N = 10*np.arange(3).reshape((1,3))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M = np.arange(9).reshape((3,3))
N = 10*np.arange(3).reshape((3,1))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M = np.arange(3).reshape((3,1))
N = 10*np.arange(3).reshape((1,3))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}')

M:
[[0 1 2]
 [3 4 5]
 [6 7 8]],ndim: 2, shape:(3, 3)
N:
[[ 0 10 20]],ndim: 2, shape:(1, 3)
M + N:
[[ 0 11 22]
 [ 3 14 25]
 [ 6 17 28]],ndim: 2, shape:(3, 3)

M:
[[0 1 2]
 [3 4 5]
 [6 7 8]],ndim: 2, shape:(3, 3)
N:
[[ 0]
 [10]
 [20]],ndim: 2, shape:(3, 1)
M + N:
[[ 0  1  2]
 [13 14 15]
 [26 27 28]],ndim: 2, shape:(3, 3)

M:
[[0]
 [1]
 [2]],ndim: 2, shape:(3, 1)
N:
[[ 0 10 20]],ndim: 2, shape:(1, 3)
M + N:
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]],ndim: 2, shape:(3, 3)


In [5]:
# --- 3rd Order Tensors
import numpy as np

M = np.arange(18).reshape((2,3,3))
N = 10*np.arange(9).reshape((1,3,3))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M = np.arange(18).reshape((2,3,3))
N = 10*np.arange(6).reshape((2,1,3))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M = np.arange(18).reshape((2,3,3))
N = 10*np.arange(6).reshape((2,3,1))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M = np.arange(6).reshape((2,1,3))
N = 10*np.arange(6).reshape((2,3,1))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}')

M:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]],ndim: 3, shape:(2, 3, 3)
N:
[[[ 0 10 20]
  [30 40 50]
  [60 70 80]]],ndim: 3, shape:(1, 3, 3)
M + N:
[[[ 0 11 22]
  [33 44 55]
  [66 77 88]]

 [[ 9 20 31]
  [42 53 64]
  [75 86 97]]],ndim: 3, shape:(2, 3, 3)

M:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]],ndim: 3, shape:(2, 3, 3)
N:
[[[ 0 10 20]]

 [[30 40 50]]],ndim: 3, shape:(2, 1, 3)
M + N:
[[[ 0 11 22]
  [ 3 14 25]
  [ 6 17 28]]

 [[39 50 61]
  [42 53 64]
  [45 56 67]]],ndim: 3, shape:(2, 3, 3)

M:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]],ndim: 3, shape:(2, 3, 3)
N:
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]],ndim: 3, shape:(2, 3, 1)
M + N:
[[[ 0  1  2]
  [13 14 15]
  [26 27 28]]

 [[39 40 41]
  [52 53 54]
  [65 66 67]]],ndim: 3, shape:(2, 3, 3)

M:
[[[0 1 2]]

 [[3 4 5]]],ndim: 3, shape:(2, 1, 3)
N:
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]],ndim: 3, shape:(2, 3, 1

### 2-2.When ndims are not equal

In [6]:
import numpy as np

a = np.array(3)
u = np.arange(1,5)
print(f'a: {a}, ndim: {a.ndim}, shape: {a.shape}')
print(f'u: {u}, ndim: {u.ndim}, shape: {u.shape}\n')

print(f'a + u: {a+u}')
print(f'a - u: {a-u}')
print(f'a * u: {a*u}')
print(f'a / u: {a/u}')
print(f'a // u: {a//u}')
print(f'a % u: {a%u}')
print(f'a ** u: {a**u}\n')

print(f'a > u: {a>u}')
print(f'a >= u: {a>=u}')
print(f'a < u: {a<u}')
print(f'a <= u: {a<=u}')
print(f'a == u: {a==u}')
print(f'a != u: {a!=u}')

a: 3, ndim: 0, shape: ()
u: [1 2 3 4], ndim: 1, shape: (4,)

a + u: [4 5 6 7]
a - u: [ 2  1  0 -1]
a * u: [ 3  6  9 12]
a / u: [3.   1.5  1.   0.75]
a // u: [3 1 1 0]
a % u: [0 1 0 3]
a ** u: [ 3  9 27 81]

a > u: [ True  True False False]
a >= u: [ True  True  True False]
a < u: [False False False  True]
a <= u: [False False  True  True]
a == u: [False False  True False]
a != u: [ True  True False  True]


In [7]:
import numpy as np

M = 10*np.arange(1,3)
N = np.arange(6).reshape((3,2))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M = np.arange(24).reshape((2,3,4))
N = 10*np.arange(12).reshape((3,4))
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M = np.arange(24).reshape((2,3,4))
N = 10*np.arange(4)
print(f'M:\n{M},ndim: {M.ndim}, shape:{M.shape}')
print(f'N:\n{N},ndim: {N.ndim}, shape:{N.shape}')
print(f'M + N:\n{M+N},ndim: {(M+N).ndim}, shape:{(M+N).shape}\n')

M:
[10 20],ndim: 1, shape:(2,)
N:
[[0 1]
 [2 3]
 [4 5]],ndim: 2, shape:(3, 2)
M + N:
[[10 21]
 [12 23]
 [14 25]],ndim: 2, shape:(3, 2)

M:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]],ndim: 3, shape:(2, 3, 4)
N:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]],ndim: 2, shape:(3, 4)
M + N:
[[[  0  11  22  33]
  [ 44  55  66  77]
  [ 88  99 110 121]]

 [[ 12  23  34  45]
  [ 56  67  78  89]
  [100 111 122 133]]],ndim: 3, shape:(2, 3, 4)

M:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]],ndim: 3, shape:(2, 3, 4)
N:
[ 0 10 20 30],ndim: 1, shape:(4,)
M + N:
[[[ 0 11 22 33]
  [ 4 15 26 37]
  [ 8 19 30 41]]

 [[12 23 34 45]
  [16 27 38 49]
  [20 31 42 53]]],ndim: 3, shape:(2, 3, 4)

