## 1.행렬 ndarray에서의 axis, keepdims

### 1-1.np.sum and ndarray.sum of Vector

In [1]:
import numpy as np

a = np.arange(5)
print(f'ndarray: {a}\n')

print(f'np.sum: {np.sum(a)}')
print(f'ndarray.sum: {a.sum()}')

ndarray: [0 1 2 3 4]

np.sum: 10
ndarray.sum: 10


### 1-2.np.sum and ndarray.sum of Matrix

In [2]:
import numpy as np

a = np.arange(6).reshape((2,-1))
print(f'ndarray:\n{a}\n')

print(f'np.sum: {np.sum(a)}')
print(f'ndarray.sum: {a.sum()}')

ndarray:
[[0 1 2]
 [3 4 5]]

np.sum: 15
ndarray.sum: 15


### 1-3.axis Argument

In [3]:
import numpy as np

a = np.arange(12).reshape((3,-1))
print(f'scores:\n{a}\n')

sum_class = a.sum(axis=0)
print(f'sum_class(axis=0): {sum_class}, shape: {sum_class.shape}')

sum_student = a.sum(axis=1)
print(f'sum_student(axis=1): {sum_student}, shape: {sum_student.shape}')

scores:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

sum_class(axis=0): [12 15 18 21], shape: (4,)
sum_student(axis=1): [ 6 22 38], shape: (3,)


### 1-4.Keepdims Argument

In [4]:
import numpy as np

a = np.arange(12).reshape((3,-1))
print(f'scores:\n{a}\n')

sum_class = np.sum(a, axis=0, keepdims=True)
print(f'sum_class(axis=0):\n{sum_class}, shape: {sum_class.shape}')

sum_student = np.sum(a, axis=1, keepdims=True)
print(f'sum_student(axis=1):\n{sum_student}, shape: {sum_student.shape}')

scores:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

sum_class(axis=0):
[[12 15 18 21]], shape: (1, 4)
sum_student(axis=1):
[[ 6]
 [22]
 [38]], shape: (3, 1)


### 1-5.Mean Subtraction

In [5]:
import numpy as np

n_student, n_class = 3,4
m_score, M_score = 0, 100
scores = np.random.randint(low=m_score, high=M_score,
                           size = (n_student,n_class))

print(f'scores:\n{scores}\n')

mean_class = np.mean(scores, axis=0, keepdims=True)
print(f'mean_class(axis=0):\n{mean_class}, shape: {mean_class.shape}')

mean_student = np.mean(scores, axis=1, keepdims=True)
print(f'mean_student(axis=1):\n{mean_student}, shape: {mean_student.shape}\n')

print(f'Mean Subtraction by classes:\n{scores - mean_class}')
print(f'Mean Subtraction by students:\n{scores - mean_student}')

scores:
[[85 77 14 19]
 [72 24 19  7]
 [32 15 52  3]]

mean_class(axis=0):
[[63.         38.66666667 28.33333333  9.66666667]], shape: (1, 4)
mean_student(axis=1):
[[48.75]
 [30.5 ]
 [25.5 ]], shape: (3, 1)

Mean Subtraction by classes:
[[ 22.          38.33333333 -14.33333333   9.33333333]
 [  9.         -14.66666667  -9.33333333  -2.66666667]
 [-31.         -23.66666667  23.66666667  -6.66666667]]
Mean Subtraction by students:
[[ 36.25  28.25 -34.75 -29.75]
 [ 41.5   -6.5  -11.5  -23.5 ]
 [  6.5  -10.5   26.5  -22.5 ]]


## 2.텐서 ndarray에서의 axis, keepdims

### 2-1.axis, keepdims

In [6]:
import numpy as np

a = np.arange(24).reshape((2,3,-1))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

sum = a.sum(axis=0)
print(f'sum(axis=0):\n{sum}, shape: {sum.shape}')
sum = a.sum(axis=0, keepdims=True)
print(f'sum(axis=0, keepdims=True):\n{sum}, shape: {sum.shape}\n')

sum = a.sum(axis=1)
print(f'sum(axis=1):\n{sum}, shape: {sum.shape}')
sum = a.sum(axis=1, keepdims=True)
print(f'sum(axis=1, keepdims=True):\n{sum}, shape: {sum.shape}\n')

sum = a.sum(axis=2)
print(f'sum(axis=2):\n{sum}, shape: {sum.shape}')
sum = a.sum(axis=2, keepdims=True)
print(f'sum(axis=2, keepdims=True):\n{sum}, shape: {sum.shape}\n')

ndarray:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape: (2, 3, 4)

sum(axis=0):
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]], shape: (3, 4)
sum(axis=0, keepdims=True):
[[[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]], shape: (1, 3, 4)

sum(axis=1):
[[12 15 18 21]
 [48 51 54 57]], shape: (2, 4)
sum(axis=1, keepdims=True):
[[[12 15 18 21]]

 [[48 51 54 57]]], shape: (2, 1, 4)

sum(axis=2):
[[ 6 22 38]
 [54 70 86]], shape: (2, 3)
sum(axis=2, keepdims=True):
[[[ 6]
  [22]
  [38]]

 [[54]
  [70]
  [86]]], shape: (2, 3, 1)



### 2-2.Example

In [7]:
import numpy as np

n_test_time, n_student, n_class = 4, 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low=m_score, high=M_score,
                           size = (n_test_time, n_student, n_class))

print(f'scores:\n{scores}, shape: {scores.shape}\n')

test_mean = np.mean(scores, axis=0)
print(f'test_mean:\n{test_mean}, shape: {test_mean.shape}\n')

class_mean = np.mean(scores, axis=1, keepdims=True)
print(f'class_mean:\n{class_mean}, shape: {class_mean.shape}\n')

student_mean = np.mean(scores, axis=2, keepdims=True)
print(f'student_mean:\n{student_mean}, shape: {student_mean.shape}')

scores:
[[[ 7 56 16 60]
  [ 7 90 12 27]
  [93 45  1 31]]

 [[ 2 32 45 88]
  [94 29 39 33]
  [47 53 73 17]]

 [[78 43 98 45]
  [34 40 28 32]
  [26 50 52 50]]

 [[31 84 73 80]
  [59 59 20 56]
  [88 31 85 79]]], shape: (4, 3, 4)

test_mean:
[[29.5  53.75 58.   68.25]
 [48.5  54.5  24.75 37.  ]
 [63.5  44.75 52.75 44.25]], shape: (3, 4)

class_mean:
[[[35.66666667 63.66666667  9.66666667 39.33333333]]

 [[47.66666667 38.         52.33333333 46.        ]]

 [[46.         44.33333333 59.33333333 42.33333333]]

 [[59.33333333 58.         59.33333333 71.66666667]]], shape: (4, 1, 4)

student_mean:
[[[34.75]
  [34.  ]
  [42.5 ]]

 [[41.75]
  [48.75]
  [47.5 ]]

 [[66.  ]
  [33.5 ]
  [44.5 ]]

 [[67.  ]
  [48.5 ]
  [70.75]]], shape: (4, 3, 1)


In [8]:
import numpy as np

C,H,W = 3,100,200

# (C,H,W) case
image = np.random.randint(0, 256, size =(C,H,W))
print(f'Shape of original image: {image.shape}')

gray_image = np.mean(image, axis=0)
print(f'Shape of gray-scaled image: {gray_image.shape}\n')

# (H,W,C) case
image = np.random.randint(0, 256, size =(H,W,C))
print(f'Shape of original image: {image.shape}')

gray_image = np.mean(image, axis=-1, keepdims=True) # axis=-1: 마지막 차원
print(f'Shape of gray-scaled image: {gray_image.shape}')

Shape of original image: (3, 100, 200)
Shape of gray-scaled image: (100, 200)

Shape of original image: (100, 200, 3)
Shape of gray-scaled image: (100, 200, 1)
