## 1.ndarray의 합곱차 구하기


### 1-1.summation
- np.cumsum(a, axis=None, dtype=None, out=None)
- ndarray.cumsum(a, axis=None, dtype=None, out=None)

In [1]:
import numpy as np

a = np.arange(5)
print(f'ndarray: {a}\n')

cumsum = np.cumsum(a)
print(f'cumsum: {cumsum}')

ndarray: [0 1 2 3 4]

cumsum: [ 0  1  3  6 10]


In [2]:
import numpy as np

a = np.arange(12).reshape((3,-1))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

cumsum = np.cumsum(a)
print(f'cumsum:\n{cumsum}, shape: {cumsum.shape}\n')

cumsum = np.cumsum(a, axis=0)
print(f'cumsum(axis=0):\n{cumsum}, shape: {cumsum.shape}\n')

cumsum = np.cumsum(a, axis=1)
print(f'cumsum(axis=1):\n{cumsum}, shape: {cumsum.shape}')

ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape: (3, 4)

cumsum:
[ 0  1  3  6 10 15 21 28 36 45 55 66], shape: (12,)

cumsum(axis=0):
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]], shape: (3, 4)

cumsum(axis=1):
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]], shape: (3, 4)


### 1-2.Product
- np.prod(a, axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- np.cumprod(a ,axis=None, dtype=None, out=None)

In [3]:
import numpy as np

a = np.arange(1, 5)
print(f'ndarray: {a}\n')

prod = np.prod(a)
cumprod = np.cumprod(a)
print(f'prod: {prod}')
print(f'cumprod: {cumprod}, shape: {cumprod.shape}')

ndarray: [1 2 3 4]

prod: 24
cumprod: [ 1  2  6 24], shape: (4,)


In [4]:
import numpy as np

a = np.arange(1,13).reshape((3,-1))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

prod = np.prod(a, axis=0)
cumprod = np.cumprod(a, axis=0)
print(f'prod(axis=0):\n{prod}, shape: {prod.shape}\n')
print(f'cumprod(axis=0):\n{cumprod}, shape: {cumprod.shape}\n')

prod = np.prod(a, axis=1, keepdims=True)
cumprod = np.cumprod(a, axis=1)
print(f'prod(axis=1, keepdims=True):\n{prod}, shape: {prod.shape}\n')
print(f'cumprod(axis=1):\n{cumprod}, shape: {cumprod.shape}')

ndarray:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape: (3, 4)

prod(axis=0):
[ 45 120 231 384], shape: (4,)

cumprod(axis=0):
[[  1   2   3   4]
 [  5  12  21  32]
 [ 45 120 231 384]], shape: (3, 4)

prod(axis=1, keepdims=True):
[[   24]
 [ 1680]
 [11880]], shape: (3, 1)

cumprod(axis=1):
[[    1     2     6    24]
 [    5    30   210  1680]
 [    9    90   990 11880]], shape: (3, 4)


### 1-3.Difference
- np.diff(a, n=1, axis=-1, prepend=no value, append=no value)

In [5]:
import numpy as np

a = np.random.randint(0,10,(5,))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

diff = np.diff(a)
print(f'diff:\n{diff}, shape: {diff.shape}')

ndarray:
[6 6 6 1 0], shape: (5,)

diff:
[ 0  0 -5 -1], shape: (4,)


In [6]:
import numpy as np

a = np.random.randint (0,10,(4,4))
print(f'ndarray:\n{a}, shape: {a.shape}\n')

diff = np.diff(a, axis=0)
print(f'diff(axis=0):\n{diff}, shape: {diff.shape}\n')

diff = np.diff(a, axis=1)
print(f'diff(axis=1):\n{diff}, shape: {diff.shape}')

ndarray:
[[8 4 8 4]
 [4 5 7 2]
 [9 3 9 7]
 [6 7 7 1]], shape: (4, 4)

diff(axis=0):
[[-4  1 -1 -2]
 [ 5 -2  2  5]
 [-3  4 -2 -6]], shape: (3, 4)

diff(axis=1):
[[-4  4 -4]
 [ 1  2 -5]
 [-6  6 -2]
 [ 1  0 -6]], shape: (4, 3)


## 2.ndarray의 통계값 구하기

### 2-1.Mean vs Average
- np.mean(a, axis=None, dtype=None, out=None, keepdims=no value, *, where=no value)
- ndarray.mean(axis=None, dtype=None, out=None, keepdims=no value, *, where=no value)

In [7]:
import numpy as np

x = np.random.randint(1,10,(5,))
w = np.array([1,2,3,4,5])
w = w/w.sum()
print(f'ndarry:\n{x}\n')

mean = np.mean(x)
print(f'mean: {np.mean(x)}\n')

print(f'weigths: {w}')
print(f'average: {np.average(x, weights=w)}')

print(f'np.sum(x*w): {np.sum(x*w)}')

ndarry:
[9 4 7 1 2]

mean: 4.6

weigths: [0.06666667 0.13333333 0.2        0.26666667 0.33333333]
average: 3.4666666666666663
np.sum(x*w): 3.4666666666666663


### 2-2.Median
np.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

In [8]:
import numpy as np

x = np.arange(9)
median = np.median(x)
print(f'ndarray:\n{x}, median: {median}\n')

x = np.arange(10)
median = np.median(x)
print(f'ndarray:\n{x}, median: {median}')

ndarray:
[0 1 2 3 4 5 6 7 8], median: 4.0

ndarray:
[0 1 2 3 4 5 6 7 8 9], median: 4.5


In [9]:
import numpy as np

x = np.random.randint(1,10, (100,))
print(f'ndarry:\n{x}\n')

mean = np.mean(x)
median = np.median(x)
print(f'mean/median: {mean} / {median}\n')

x = np.append(x, 1000)
mean = np.mean(x)
median = np.median(x)
print(f'mean/median: {mean} / {median}') # mean은 outlier에 민감하여 커지는것을 볼수있다

ndarry:
[2 1 9 7 9 6 2 6 4 3 5 4 1 7 5 1 7 7 5 6 3 2 7 6 9 2 6 7 6 2 2 7 2 5 8 4 5
 9 5 1 2 4 6 5 6 3 5 2 3 7 5 3 8 4 9 7 3 9 3 1 2 6 1 8 6 1 2 4 6 1 8 1 3 5
 3 7 6 3 3 5 2 8 9 8 5 9 6 5 4 8 4 8 7 6 6 9 6 7 6 6]

mean/median: 5.0 / 5.0

mean/median: 14.851485148514852 / 5.0


### 2-3.Variance and Standard Deviation
- np.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)
- ndarray.var(axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)
- np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)
- ndarray.std(axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *,where=no value)

In [10]:
import numpy as np

scores = np.random.normal(10,5, (100,))

var = scores.var()
std = scores.std()

print(f'variance: {var}')
print(f'standard deviation: {std}')

variance: 26.56026079118169
standard deviation: 5.153664792279538


### 2-4.Standardization

In [11]:
import numpy as np

means = [50,60,70]
stds = [3,5,10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means, scale=stds,
                          size=(n_student,n_class))
scores = scores.astype(np.float32)


mean = np.mean(scores, axis=0)
std = np.std(scores, axis=0)
print(f'Shape of scores: {scores.shape}, dtype: {scores.dtype}')
print(f'Mean: {mean}, shape = {mean.shape}')
print(f'Std: {std}, shape = {std.shape}\n')

score_stdz = (scores - mean)/std
mean = np.mean(score_stdz, axis=0)
std = np.std(score_stdz, axis=0)
print(f'Shape of scores: {score_stdz.shape}')
print(f'Mean: {mean}, shape = {mean.shape}')
print(f'Std: {std}, shape = {std.shape}')

Shape of scores: (100, 3), dtype: float32
Mean: [49.91644  60.158325 72.32298 ], shape = (3,)
Std: [ 2.919888  5.050794 10.49792 ], shape = (3,)

Shape of scores: (100, 3)
Mean: [-9.5069410e-08  1.3911724e-06 -1.4662743e-06], shape = (3,)
Std: [1.0000001 1.        0.9999998], shape = (3,)


### 2-5.Max Values and Indices
- np.amax(a, axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- ndarray.max(axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- np.argmax(a, axis=None, out=None)
- ndarray.argmax(axis=None, out=None)

In [12]:
import numpy as np

a = np.random.randint(0,100, (10,))
print(f'ndarray:\n{a}')

M = np.max(a)
M_idx = np.argmax(a)
print(f'M/M_idx: {M}/{M_idx}')

ndarray:
[52 80 28 62 42 60 95  3 58 48]
M/M_idx: 95/6


In [13]:
import numpy as np

means = [50,60,70]
stds = [3,5,10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means, scale=stds,
                          size=(n_student,n_class))
scores = scores.astype(np.float32)
print(f'Shape of scores: {scores.shape}, dtype: {scores.dtype}\n')

scores_max = np.max(scores, axis=0)
scores_max_idx = np.argmax(scores, axis=0)
print(f'max scores(axis=0): {scores_max}, shape: {scores_max.shape}')
print(f'max indices(axis=0): {scores_max_idx}, shape: {scores_max_idx.shape}\n')

scores_max = np.max(scores, axis=1)
scores_max_idx = np.argmax(scores, axis=1)
print(f'Shape of max scores(axis=1): {scores_max.shape}')
print(f'Shape of max indices(axis=1): {scores_max_idx.shape}')

Shape of scores: (100, 3), dtype: float32

max scores(axis=0): [56.880493 73.5448   90.81731 ], shape: (3,)
max indices(axis=0): [ 3 70 40], shape: (3,)

Shape of max scores(axis=1): (100,)
Shape of max indices(axis=1): (100,)


### 2-6.Min Values and Indices
- np.amin(a, axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- ndarray.min(axis=None, dtype=None, out=None, keepdims=no value, initial=no value, where=no value)
- np.argmin(a, axis=None, out=None)
- ndarray.argmin(axis=None, out=None)

In [14]:
# Min-max Normalization
import numpy as np

means = [50,60,70]
stds = [3,5,10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means, scale=stds,
                          size=(n_student,n_class))
scores = scores.astype(np.float32)
print(f'Shape of scores: {scores.shape}, dtype:{scores.dtype}')

M = np.max(scores, axis=0)
m = np.min(scores, axis=0)
print(f'max values: {M}, shape: {M.shape}')
print(f'min values: {m}, shape: {m.shape}\n')

score_nor = (scores - m)/(M-m)
print(f'Shape of Normalization: {score_nor.shape}')
M = np.max(score_nor, axis=0)
m = np.min(score_nor, axis=0)
print(f'Max Values: {M}, shape: {M.shape}')
print(f'min Values: {m}, shape: {m.shape}')

Shape of scores: (100, 3), dtype:float32
max values: [60.29157  72.62524  97.204185], shape: (3,)
min values: [42.12356 49.16649 44.20255], shape: (3,)

Shape of Normalization: (100, 3)
Max Values: [1. 1. 1.], shape: (3,)
min Values: [0. 0. 0.], shape: (3,)


### 2-7.Maximun and Minimum

In [15]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.maximum(u, v)
print(f'maximum: {maximum}, shape: {maximum.shape}')
minimum = np.minimum(u, v)
print(f'minimum: {minimum}, shape: {minimum.shape}')

u:
[5 2 6 3 5 0 8 9 0 4], shape: (10,)
v:
[5 5 0 3 5 8 6 3 5 8], shape: (10,)

maximum: [5 5 6 3 5 8 8 9 5 8], shape: (10,)
minimum: [5 2 0 3 5 0 6 3 0 4], shape: (10,)


In [16]:
import numpy as np

u = np.random.randint(0,10, (3,4))
v = np.random.randint(0,10, (3,4))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.maximum(u, v)
print(f'maximum:\n{maximum}, shape: {maximum.shape}')
minimum = np.minimum(u, v)
print(f'minimum:\n{minimum}, shape: {minimum.shape}')

u:
[[0 1 8 7]
 [3 8 4 3]
 [3 9 9 0]], shape: (3, 4)
v:
[[0 8 2 4]
 [9 9 4 3]
 [9 9 5 7]], shape: (3, 4)

maximum:
[[0 8 8 7]
 [9 9 4 3]
 [9 9 9 7]], shape: (3, 4)
minimum:
[[0 1 2 4]
 [3 8 4 3]
 [3 9 5 0]], shape: (3, 4)


In [17]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.zeros_like(u)
maximum[u >= v] = u[u >= v]
maximum[v > u] = v[v > u]
print(f'maximum:\n{maximum}, shape: {maximum.shape}')

minimum = np.zeros_like(u)
minimum[u <= v] = u[u <= v]
minimum[v < u] = v[v < u]
print(f'minimum:\n{minimum}, shape: {minimum.shape}')

u:
[3 5 6 5 9 9 5 7 1 5], shape: (10,)
v:
[3 3 9 8 5 1 8 8 7 0], shape: (10,)

maximum:
[3 5 9 8 9 9 8 8 7 5], shape: (10,)
minimum:
[3 3 6 5 5 1 5 7 1 0], shape: (10,)


In [18]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

# u가 더크면 100, v가 더 크면 -100
up_vals = np.full_like(u, fill_value=100)
down_vals = np.full_like(u, fill_value=-100)
print(np.where(u>v, up_vals, down_vals))

u:
[9 8 6 4 6 9 4 0 8 7], shape: (10,)
v:
[9 4 4 8 5 9 6 8 7 1], shape: (10,)

[-100  100  100 -100  100 -100 -100 -100  100  100]


In [19]:
import numpy as np

u = np.random.randint(0,10, (10,))
v = np.random.randint(0,10, (10,))
print(f'u:\n{u}, shape: {u.shape}')
print(f'v:\n{v}, shape: {v.shape}\n')

maximum = np.maximum(u,v)
maximum_where = np.where(u>v,u,v)
print(f'maximum:\n{maximum}, shape: {maximum.shape}')
print(f'maximum(where): \n{maximum_where}, shape: {maximum_where.shape}\n')

minimum = np.minimum(u,v)
minimum_where = np.where(u<v,u,v)
print(f'minimum:\n{minimum}, shape: {minimum.shape}')
print(f'minimum(where): \n{minimum_where}, shape: {minimum_where.shape}')

u:
[8 1 1 9 9 8 4 8 7 5], shape: (10,)
v:
[8 4 4 8 9 7 7 3 8 4], shape: (10,)

maximum:
[8 4 4 9 9 8 7 8 8 5], shape: (10,)
maximum(where): 
[8 4 4 9 9 8 7 8 8 5], shape: (10,)

minimum:
[8 1 1 8 9 7 4 3 7 4], shape: (10,)
minimum(where): 
[8 1 1 8 9 7 4 3 7 4], shape: (10,)
