## 1.Rounding Functions


### 1-1.반올림 API
- np.around(a, decimals=0, out=None)
- np.round_(a, decimals=0, out=None)
- ndarray.round(decimals=0, out=None)

In [1]:
import numpy as np

x = np.random.uniform(-5,5, (5,))
print(f'x:\n{x}\n')

np_around = np.around(x, decimals=2)
np_round_ = np.round_(x, decimals=2)
x_round = x.round(decimals=2)

print(f'np_around:\n{np_around}')
print(f'np_round_:\n{np_round_}')
print(f'x_round:\n{x_round}')

x:
[-1.16624646 -0.84412343 -0.4631444   2.3256977   4.20023477]

np_around:
[-1.17 -0.84 -0.46  2.33  4.2 ]
np_round_:
[-1.17 -0.84 -0.46  2.33  4.2 ]
x_round:
[-1.17 -0.84 -0.46  2.33  4.2 ]


In [2]:
import numpy as np

scores = np.random.uniform(0,100, (100,5))

means = np.mean(scores, axis=0)
stds = np.std(scores, axis=0)

print(f'calss means:\n{means}')
print(f'class stds:\n{stds}\n')

print(f'calss means:\n{means.round(2)}')
print(f'class stds:\n{stds.round(2)}\n')

calss means:
[51.31589812 50.08284328 55.02746552 49.37381213 48.76399553]
class stds:
[28.71380351 30.94162838 28.43739461 29.98751621 30.42707738]

calss means:
[51.32 50.08 55.03 49.37 48.76]
class stds:
[28.71 30.94 28.44 29.99 30.43]



### 1-2.올림,버림 API
- np.ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[,signature,extobj])
- np.floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[,signature,extobj])

In [3]:
import numpy as np

x = np.random.uniform(-5,5, (5,))
print(f'x:\n{x}\n')

ceil = np.ceil(x)
floor = np.floor(x)
print(f'ceil:\n{ceil}')   # 올림
print(f'floor:\n{floor}') # 버림

x:
[-4.90662943  1.49823102  3.50770309 -3.70001337  4.59969175]

ceil:
[-4.  2.  4. -3.  5.]
floor:
[-5.  1.  3. -4.  4.]


### 1-3.Truncation Functions
np.trunc(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[,signature,extobj])

In [4]:
import numpy as np

x = np.random.uniform(-5,5, (5,))
print(f'x:\n{x}\n')

trunc = np.trunc(x)
print(f'trunc:\n{trunc}')

x:
[ 3.21398877 -0.37365306  1.72285004  2.14765334  4.74173079]

trunc:
[ 3. -0.  1.  2.  4.]


In [5]:
import numpy as np

x = np.random.uniform(-5,5, (5,))
print(f'x:\n{x}\n')

trunc = np.trunc(x)
trunc_where = np.where(x >= 0, np.floor(x), np.ceil(x))
print(f'trunc:\n{trunc}')
print(f'trunc_where:\n{trunc_where}')

x:
[ 2.52707931 -0.94743817  0.86876078  0.3128041  -1.67268071]

trunc:
[ 2. -0.  0.  0. -1.]
trunc_where:
[ 2. -0.  0.  0. -1.]


In [6]:
import numpy as np

x = np.random.uniform(-5,5, (5,))
print(f'x:\n{x}\n')

# 소수점 둘째자리까지 나타내기
trunc = 0.01*np.trunc(100*x)
print(f'trunc:\n{trunc}')

x:
[-0.56375118  1.04354811  1.09793516 -4.46519922  0.54902654]

trunc:
[-0.56  1.04  1.09 -4.46  0.54]


In [7]:
import numpy as np

x = np.random.uniform(-5,5, (5,))
print(f'x:\n{x}\n')

# 정수 부분, 소수 부분
int_part = np.trunc(x)
frac_part = x - int_part
print(f'int_part:\n{int_part}')
print(f'frac_part:\n{frac_part}')

x:
[ 2.95860895  3.44229459  3.77622027 -0.93347978 -0.272304  ]

int_part:
[ 2.  3.  3. -0. -0.]
frac_part:
[ 0.95860895  0.44229459  0.77622027 -0.93347978 -0.272304  ]


## 2.Sorting Functions
- np.sort(a, axis=-1, kind=None, order=None)
- np.argsort(a, axis=-1, kind=None, order=None)

### 2-1.Sorting Vectors

In [8]:
import numpy as np

x = np.random.randint(0,100, (10,))
print(f'x:\n{x}\n')

# 오름차순(ascending)
sort = np.sort(x)
argsort = np.argsort(x)
print(f'sort:\n{sort}')
print(f'argsort:\n{argsort}\n')

# 내림차순(descending)
sort = np.sort(x)[::-1]
argsort = np.argsort(x)[::-1]
print(f'sort:\n{sort}')
print(f'argsort:\n{argsort}')

x:
[84 77 42 40 38 62 11 43 80 16]

sort:
[11 16 38 40 42 43 62 77 80 84]
argsort:
[6 9 4 3 2 7 5 1 8 0]

sort:
[84 80 77 62 43 42 40 38 16 11]
argsort:
[0 8 1 5 7 2 3 4 9 6]


In [9]:
# top3-Accuracy
import numpy as np

pred = np.random.uniform(0,100, (5,))
pred /= pred.sum()
print(f'pred:\n{pred.round(3)}\n')

top3_pred = np.sort(pred)[::-1][:3]
top3_indices = np.argsort(pred)[::-1][:3]
print(f'top3_pred:\n{top3_pred.round(3)}')
print(f'top3_indices:\n{top3_indices}')

pred:
[0.156 0.257 0.26  0.113 0.213]

top3_pred:
[0.26  0.257 0.213]
top3_indices:
[2 1 4]


### 2-2.Sorting Matrics

In [10]:
# 오름차순(ascending)
import numpy as np

x = np.random.randint(0,100, (4,5))
print(f'x:\n{x}\n')

sort = np.sort(x, axis=0)
argsort = np.argsort(x, axis=0)
print(f'sort(axis=0):\n{sort}')
print(f'argsort(axis=0):\n{argsort}\n')

sort = np.sort(x, axis=1)
argsort = np.argsort(x, axis=1)
print(f'sort(axis=1):\n{sort}')
print(f'argsort(axis=1):\n{argsort}')

x:
[[22 59 67 31 81]
 [99 87 18 92 42]
 [22 56 91 67 10]
 [68 22 23 93 20]]

sort(axis=0):
[[22 22 18 31 10]
 [22 56 23 67 20]
 [68 59 67 92 42]
 [99 87 91 93 81]]
argsort(axis=0):
[[0 3 1 0 2]
 [2 2 3 2 3]
 [3 0 0 1 1]
 [1 1 2 3 0]]

sort(axis=1):
[[22 31 59 67 81]
 [18 42 87 92 99]
 [10 22 56 67 91]
 [20 22 23 68 93]]
argsort(axis=1):
[[0 3 1 2 4]
 [2 4 1 3 0]
 [4 0 1 3 2]
 [4 1 2 0 3]]


In [11]:
# 내림차순(descending)
import numpy as np

x = np.random.randint(0,100, (4,5))
print(f'x:\n{x}\n')

sort = np.sort(x, axis=0)[::-1, :]
argsort = np.argsort(x, axis=0)[::-1, :]
print(f'sort(axis=0):\n{sort}')
print(f'argsort(axis=0):\n{argsort}\n')

sort = np.sort(x, axis=1)[:, ::-1]
argsort = np.argsort(x, axis=1)[:, ::-1]
print(f'sort(axis=1):\n{sort}')
print(f'argsort(axis=1):\n{argsort}')

x:
[[11 81 67 28 92]
 [22  1 17 67 27]
 [16 30 10 16 84]
 [70  1 93 87 60]]

sort(axis=0):
[[70 81 93 87 92]
 [22 30 67 67 84]
 [16  1 17 28 60]
 [11  1 10 16 27]]
argsort(axis=0):
[[3 0 3 3 0]
 [1 2 0 1 2]
 [2 3 1 0 3]
 [0 1 2 2 1]]

sort(axis=1):
[[92 81 67 28 11]
 [67 27 22 17  1]
 [84 30 16 16 10]
 [93 87 70 60  1]]
argsort(axis=1):
[[4 1 2 3 0]
 [3 4 0 2 1]
 [4 1 3 0 2]
 [2 3 0 4 1]]


In [12]:
# top2-Students
import numpy as np

scores = np.random.randint(0,100, (5,3))
print(f'scores:\n{scores}\n')

sort = np.sort(scores, axis=0)[::-1, :]
argsort = np.argsort(scores, axis=0)[::-1, :]
print(f'sort:\n{sort}')
print(f'argsort:\n{argsort}\n')

print(f'top2-scores:\n{sort[:2, :]}')
print(f'top2-students:\n{argsort[:2, :]}')

scores:
[[80 35 94]
 [28  0 70]
 [33 55 75]
 [59 49 59]
 [88 34 63]]

sort:
[[88 55 94]
 [80 49 75]
 [59 35 70]
 [33 34 63]
 [28  0 59]]
argsort:
[[4 2 0]
 [0 3 2]
 [3 0 1]
 [2 4 4]
 [1 1 3]]

top2-scores:
[[88 55 94]
 [80 49 75]]
top2-students:
[[4 2 0]
 [0 3 2]]


In [13]:
# bottom2-Classes
import numpy as np

scores = np.random.randint(0,100, (5,3))
print(f'scores:\n{scores}\n')

sort = np.sort(scores, axis=1)
argsort = np.argsort(scores, axis=1)
print(f'sort:\n{sort}')
print(f'argsort:\n{argsort}\n')

print(f'bottom2-scores:\n{sort[:, :2]}')
print(f'bottom2-classes:\n{argsort[:, :2]}')

scores:
[[99 88 99]
 [50 17 27]
 [36 22 91]
 [26 18 34]
 [ 6 30 34]]

sort:
[[88 99 99]
 [17 27 50]
 [22 36 91]
 [18 26 34]
 [ 6 30 34]]
argsort:
[[1 0 2]
 [1 2 0]
 [1 0 2]
 [1 0 2]
 [0 1 2]]

bottom2-scores:
[[88 99]
 [17 27]
 [22 36]
 [18 26]
 [ 6 30]]
bottom2-classes:
[[1 0]
 [1 2]
 [1 0]
 [1 0]
 [0 1]]
