## 1.Vector Operations


### 1-1.Dot Product
- np.dot(a,b)

In [1]:
import numpy as np

u = np.random.uniform(0, 5, (4, ))
v = np.random.uniform(0, 5, (4, ))
print(f'u:\n{u.round(2)}')
print(f'v:\n{v.round(2)}\n')

sum_hadamard = np.sum(u*v)
np_dot = np.dot(u, v)
print(f'sum_hadamard:\n{sum_hadamard}')
print(f'np_dot:\n{np_dot}')

u:
[3.24 4.05 3.36 2.65]
v:
[1.02 3.63 4.39 4.16]

sum_hadamard:
43.807622880130175
np_dot:
43.807622880130175


### 1-2.Operations of a Artificial Neuron

In [2]:
import numpy as np

x = np.random.uniform(0, 5, (4, ))
w = np.random.uniform(0, 5, (4, ))  # weight(가중치)
b= np.random.uniform(0, 5, ()) # bias
print(f'x: {x.round(3)}')
print(f'weights: {w.round(3)}')
print(f'bias: {b.round(3)}\n')

affine = np.dot(x,w) + b
sigmoid = 1/(1 + np.exp(-affine))
print(f'affine: {affine.round(3)}')
print(f'sigmoid: {sigmoid}')

x: [2.305 0.489 2.49  2.628]
weights: [4.279 0.772 4.717 0.932]
bias: 0.436

affine: 24.871
sigmoid: 0.9999999999841946


## 2.Matrix Operations
- np.matmul(x1, x2)

### 2-1.Matrix-vector Multiplication

In [3]:
import numpy as np

M = np.random.uniform(0, 5 , (3,4))
u = np.random.uniform(0, 5 , (4, ))
print(f'M:\n{M.round(2)}, shape: {M.shape}')
print(f'u:\n{u.round(2)}, shape: {u.shape}\n')

mat_vec_mul = np.empty((3, ))
for row_idx, row in enumerate(M):
    mat_vec_mul[row_idx] = np.dot(row, u)
print(f'mat_vec_mul:\n{mat_vec_mul.round(2)}, shape: {mat_vec_mul.shape}')

np_matmul = np.matmul(M, u)
print(f'np.matmul:\n{np_matmul.round(2)}, shape: {np_matmul.shape}')

M:
[[4.33 0.04 4.52 3.03]
 [2.67 3.27 4.89 4.87]
 [1.99 3.74 4.95 1.06]], shape: (3, 4)
u:
[3.83 4.78 1.44 3.28], shape: (4,)

mat_vec_mul:
[33.22 48.84 36.08], shape: (3,)
np.matmul:
[33.22 48.84 36.08], shape: (3,)


### 2-2.Matrix-matrix Multiplication


In [4]:
M = np.random.uniform(0, 5 , (3,4))
N = np.random.uniform(0, 5 , (4,5))
print(f'M:\n{M.round(2)}, shape: {M.shape}')
print(f'u:\n{N.round(2)}, shape: {N.shape}\n')

mat_mat_mul = np.empty((3,5))
for row_idx, row in enumerate(M):                                               # for M_row_idx in range(3):
    for col_idx, col in enumerate(N.transpose()):                               #   for N_col_idx in range(5):
        mat_mat_mul[row_idx, col_idx] = np.dot(row, col)                        #       dot_prod = np.dot(M[M_row_idx, :], n[:, N_col_idx])
print(f'mat_mat_mul:\n{mat_mat_mul.round(2)}, shape:{mat_mat_mul.shape}')       #       mat_mat_mul[M_row_idx, N_col_idx] = dot_prod

np_matmul = np.matmul(M, N)
print(f'np.matmul:\n{np_matmul.round(2)}, shape: {np_matmul.shape}')

M:
[[3.78 4.44 1.87 1.09]
 [3.89 3.78 2.45 0.92]
 [4.95 2.95 3.46 1.07]], shape: (3, 4)
u:
[[2.05 1.97 2.19 0.66 0.8 ]
 [1.34 3.4  1.76 1.15 0.41]
 [4.25 4.25 1.9  2.06 0.96]
 [1.67 2.09 2.64 3.19 2.7 ]], shape: (4, 5)

mat_mat_mul:
[[23.45 32.79 22.5  14.95  9.56]
 [24.99 32.89 22.23 14.92  9.47]
 [30.56 36.74 25.4  17.21 11.34]], shape:(3, 5)
np.matmul:
[[23.45 32.79 22.5  14.95  9.56]
 [24.99 32.89 22.23 14.92  9.47]
 [30.56 36.74 25.4  17.21 11.34]], shape: (3, 5)


### 2-3.Operations of Artificial Neurons

In [5]:
import numpy as np

X = np.random.uniform(0, 5, (3,4))
W = np.random.uniform(0, 5, (4,5))
b = np.random.uniform(0, 5, (5, ))
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'W:\n{W.round(2)}, shape: {W.shape}')
print(f'b:\n{b.round(2)}, shape: {b.shape}\n')

affine = np.matmul(X, W) + b
sigmoid = 1/(1 + np.exp(-affine))
print(f'affine:\n{affine.round(2)}, shape: {affine.shape}')
print(f'sigmoid:\n{sigmoid}, shape: {sigmoid.shape}')

X:
[[2.3  0.26 4.62 3.39]
 [0.31 0.72 0.81 3.94]
 [2.22 2.7  3.67 0.09]], shape: (3, 4)
W:
[[1.74 0.26 4.78 0.79 2.06]
 [1.62 0.89 0.37 2.07 1.35]
 [2.23 0.26 4.81 4.57 0.43]
 [0.24 2.5  0.31 2.91 3.21]], shape: (4, 5)
b:
[1.85 3.77 2.92 4.57 0.63], shape: (5,)

affine:
[[17.4  14.27 37.34 37.93 18.61]
 [ 6.3  14.54  9.78 21.49 15.24]
 [18.31  7.94 32.26 28.97 10.74]], shape: (3, 5)
sigmoid:
[[0.99999997 0.99999937 1.         1.         0.99999999]
 [0.99815856 0.99999952 0.99994332 1.         0.99999976]
 [0.99999999 0.99964397 1.         1.         0.99997823]], shape: (3, 5)
