## 1.Making New Dimensions

### 1-1.Using np.reshape

In [1]:
# 1차원
import numpy as np

a = np.arange(9)
print(f'a:\n{a}, shape: {a.shape}\n')

b = a.reshape((1,9))
c = a.reshape((9,1))
print(f'b:\n{b}, shape: {b.shape}')
print(f'c:\n{c}, shape: {c.shape}\n')

d = a.reshape((1,1,9))
e = a.reshape((1,9,1))
f = a.reshape((9,1,1))
print(f'd:\n{d}, shape: {d.shape}')
print(f'e:\n{e}, shape: {e.shape}')
print(f'f:\n{f}, shape: {f.shape}')

a:
[0 1 2 3 4 5 6 7 8], shape: (9,)

b:
[[0 1 2 3 4 5 6 7 8]], shape: (1, 9)
c:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]], shape: (9, 1)

d:
[[[0 1 2 3 4 5 6 7 8]]], shape: (1, 1, 9)
e:
[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]], shape: (1, 9, 1)
f:
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]], shape: (9, 1, 1)


In [2]:
# 2차원
import numpy as np

a = np.random.normal(size=(100,200))
print(f'a.shape: {a.shape}\n')

b = a.reshape((1,100,200))
c = a.reshape((100,200,1))
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')

a.shape: (100, 200)

b.shape: (1, 100, 200)
c.shape: (100, 200, 1)


In [3]:
# Tip(unsing unpacking)
a = np.random.normal(size=(100,130))
print(f'a.shape: {a.shape}\n')

b = a.reshape((1,*a.shape))
c = a.reshape((*a.shape,1))
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')

a.shape: (100, 130)

b.shape: (1, 100, 130)
c.shape: (100, 130, 1)


### 1-2.Using Slicing

In [4]:
# 1차원
import numpy as np

a = np.arange(9)
print(f'a:\n{a}, shape: {a.shape}\n')

row_vec1 = a[np.newaxis, :]
row_vec2 = a[None, :]
print(f'row_vec1:{row_vec1}, shape: {row_vec1.shape}')
print(f'row_vec2:{row_vec2}, shape: {row_vec2.shape}\n')

col_vec1 = a[:, np.newaxis]
col_vec2 = a[:, None]
print(f'col_vec1:{col_vec1}, shape: {col_vec1.shape}')
print(f'col_vec2:{col_vec2}, shape: {col_vec2.shape}\n')

b = a[np.newaxis, np.newaxis, :]
c = a[np.newaxis, :, np.newaxis]
d = a[:, np.newaxis, np.newaxis]
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}')

a:
[0 1 2 3 4 5 6 7 8], shape: (9,)

row_vec1:[[0 1 2 3 4 5 6 7 8]], shape: (1, 9)
row_vec2:[[0 1 2 3 4 5 6 7 8]], shape: (1, 9)

col_vec1:[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]], shape: (9, 1)
col_vec2:[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]], shape: (9, 1)

b.shape: (1, 1, 9)
c.shape: (1, 9, 1)
d.shape: (9, 1, 1)


In [5]:
# 2차원
import numpy as np

a = np.random.normal(size=(100, 200))
print(f'a.shape: {a.shape}\n')

b = a[np.newaxis, ...]
c = a[..., np.newaxis]
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')

a.shape: (100, 200)

b.shape: (1, 100, 200)
c.shape: (100, 200, 1)


### 1-3.Using expand_dims API

In [6]:
import numpy as np

a = np.arange(9)
print(f'a.shape: {a.shape}\n')

b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}\n')

d = np.expand_dims(a, axis=(0,1))
e = np.expand_dims(a, axis=(0,2))
f = np.expand_dims(a, axis=(1,2))
print(f'd.shape: {d.shape}')
print(f'e.shape: {e.shape}')
print(f'f.shape: {f.shape}')

a.shape: (9,)

b.shape: (1, 9)
c.shape: (9, 1)

d.shape: (1, 1, 9)
e.shape: (1, 9, 1)
f.shape: (9, 1, 1)


In [7]:
import numpy as np

a = np.arange(9).reshape((3,3))
print(f'a.shape: {a.shape}\n')

b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)
d = np.expand_dims(a, axis=-1)
e = np.expand_dims(a, axis=(0,-1))
print(f'b.shape: {b.shape}')
print(f'd.shape: {c.shape}')
print(f'd.shape: {d.shape}')
print(f'e.shape: {e.shape}')

a.shape: (3, 3)

b.shape: (1, 3, 3)
d.shape: (3, 1, 3)
d.shape: (3, 3, 1)
e.shape: (1, 3, 3, 1)


## 2.Removing Dummy Dimensions

### 2-1.Using np.reshape

In [8]:
import numpy as np

a = np.ones(shape=(1,10))
print(f'a.shape: {a.shape}\n')

b = a.reshape((10, ))
c = a.reshape((-1,))
d = a.flatten()
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}\n')

print('-----------------------------')

e = np.ones(shape=(10,1))
print(f'e.shape: {e.shape}\n')

f = e.reshape((10, ))
g = e.reshape((-1,))
h = e.flatten()
print(f'f.shape: {f.shape}')
print(f'g.shape: {g.shape}')
print(f'h.shape: {h.shape}')

a.shape: (1, 10)

b.shape: (10,)
c.shape: (10,)
d.shape: (10,)

-----------------------------
e.shape: (10, 1)

f.shape: (10,)
g.shape: (10,)
h.shape: (10,)


In [9]:
import numpy as np

a = np.ones(shape=(1,3,4))
b = np.ones(shape=(3,4,1))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}\n')

c = a.reshape(*a.shape[1:])
d = a.reshape(*b.shape[:-1])
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}')

a.shape: (1, 3, 4)
b.shape: (3, 4, 1)

c.shape: (3, 4)
d.shape: (3, 4)


### 2-2.Using Slicing

In [10]:
import numpy as  np

a = np.arange(9).reshape((3,3))
print(f'a.shape: {a.shape}\n')

row, col = a[1, :], a[:, 1]
print(f'row.shape: {row.shape}')
print(f'col.shape: {col.shape}')

a.shape: (3, 3)

row.shape: (3,)
col.shape: (3,)


In [11]:
import numpy as np

a = np.arange(9).reshape((1,-1))
b = np.arange(9).reshape((-1,1))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}\n')

c = a[0, :]
d = b[:, 0]
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}')

a.shape: (1, 9)
b.shape: (9, 1)

c.shape: (9,)
d.shape: (9,)


In [12]:
import numpy as np

a = np.ones(shape=(1,3,4))
b = np.ones(shape=(3,4,1))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}\n')

c = a[0, ...]
d = b[..., 0]
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}')

a.shape: (1, 3, 4)
b.shape: (3, 4, 1)

c.shape: (3, 4)
d.shape: (3, 4)


### 2-3.Using squeeze API
차원값이 1인것을 전부 없애줌

In [13]:
import numpy as np

a = np.ones(shape=(1,3,4))
print(f'a.shape: {a.shape}\n')

b = np.squeeze(a)
c = a.squeeze()
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}\n')

print('----------------------')

d = np.ones(shape=(1,1,4,1,3,1))
print(f'd.shape: {d.shape}\n')

e = np.squeeze(d)
print(f'e.shape: {e.shape}')

a.shape: (1, 3, 4)

b.shape: (3, 4)
c.shape: (3, 4)

----------------------
d.shape: (1, 1, 4, 1, 3, 1)

e.shape: (4, 3)


## 3.Changing Demensions


### 3-1.Using np.swapaxes API

In [14]:
import numpy as np

a = np.random.normal(size=(3,4,5,6))
print(f'a.shape: {a.shape}\n')

b = np.swapaxes(a, 0,1)
c = np.swapaxes(a, 0,2)
d = np.swapaxes(a, 0,3)
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}')

a.shape: (3, 4, 5, 6)

b.shape: (4, 3, 5, 6)
c.shape: (5, 4, 3, 6)
d.shape: (6, 4, 5, 3)


In [15]:
import numpy as np

a = np.random.normal(size=(3,200,100))
print(f'a.shape: {a.shape}\n')

b = np.swapaxes(a, 0,-1)
print(f'b.shape: {b.shape}')

a.shape: (3, 200, 100)

b.shape: (100, 200, 3)


### 3-2.Using np.moveaxis API

In [16]:
import numpy as np

a = np.random.normal(size=(3,4,5,6))
print(f'a.shape: {a.shape}\n')

b = np.moveaxis(a, source=0, destination=1)
c = np.moveaxis(a, source=0, destination=2)
d = np.moveaxis(a, source=0, destination=3)
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}')

a.shape: (3, 4, 5, 6)

b.shape: (4, 3, 5, 6)
c.shape: (4, 5, 3, 6)
d.shape: (4, 5, 6, 3)


### 3-3.Using np.transpose API

In [17]:
import numpy as np

a = np.random.normal(size=(3,4))
print(f'a.shape: {a.shape}\n')

b = np.transpose(a)
c = a.T
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')

a.shape: (3, 4)

b.shape: (4, 3)
c.shape: (4, 3)


In [18]:
import numpy as np

a = np.random.normal(size=(3,4,5,6,7))
print(f'a.shape: {a.shape}\n')

b = np.transpose(a)
c = a.T
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')

a.shape: (3, 4, 5, 6, 7)

b.shape: (7, 6, 5, 4, 3)
c.shape: (7, 6, 5, 4, 3)


In [19]:
import numpy as np

a = np.random.normal(size=(3,4,5))
print(f'a.shape: {a.shape}\n')

b = np.transpose(a, axes=(0,1,2))
c = np.transpose(a, axes=(1,0,2))
d = np.transpose(a, axes=(1,2,0))
e = np.transpose(a, axes=(2,0,1))
f = np.transpose(a, axes=(2,1,0))
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')
print(f'b.shape: {d.shape}')
print(f'c.shape: {e.shape}')
print(f'c.shape: {f.shape}')

a.shape: (3, 4, 5)

b.shape: (3, 4, 5)
c.shape: (4, 3, 5)
b.shape: (4, 5, 3)
c.shape: (5, 3, 4)
c.shape: (5, 4, 3)
