## 1.np.hstack and np.vstack

### 1-1.Usage

In [1]:
# Vector
import numpy as np

a = np.random.randint(0, 10, (4, ))
b = np.random.randint(0, 10, (4, ))
print(f'a:\n{a}, shape: {a.shape}')
print(f'b:\n{b}, shape: {b.shape}\n')

vstack = np.vstack([a, b])
hstack = np.hstack([a, b])
print(f'vstack:\n{vstack}, shape: {vstack.shape}')
print(f'hstack:\n{hstack}, shape: {hstack.shape}')

a:
[6 0 0 1], shape: (4,)
b:
[0 4 4 6], shape: (4,)

vstack:
[[6 0 0 1]
 [0 4 4 6]], shape: (2, 4)
hstack:
[6 0 0 1 0 4 4 6], shape: (8,)


In [2]:
# Row vector
import numpy as np

a = np.random.randint(0, 10, (1, 3))
b = np.random.randint(0, 10, (1, 3))
print(f'a:\n{a}, shape: {a.shape}')
print(f'b:\n{b}, shape: {b.shape}\n')

vstack = np.vstack([a, b])
hstack = np.hstack([a, b])
print(f'vstack:\n{vstack}, shape: {vstack.shape}')
print(f'hstack:\n{hstack}, shape: {hstack.shape}')

a:
[[0 8 8]], shape: (1, 3)
b:
[[8 1 8]], shape: (1, 3)

vstack:
[[0 8 8]
 [8 1 8]], shape: (2, 3)
hstack:
[[0 8 8 8 1 8]], shape: (1, 6)


In [3]:
# Colums vector
import numpy as np

a = np.random.randint(0, 10, (3, 1))
b = np.random.randint(0, 10, (3, 1))
print(f'a:\n{a}, shape: {a.shape}')
print(f'b:\n{b}, shape: {b.shape}\n')

vstack = np.vstack([a, b])
hstack = np.hstack([a, b])
print(f'vstack:\n{vstack}, shape: {vstack.shape}')
print(f'hstack:\n{hstack}, shape: {hstack.shape}')

a:
[[2]
 [2]
 [4]], shape: (3, 1)
b:
[[8]
 [4]
 [0]], shape: (3, 1)

vstack:
[[2]
 [2]
 [4]
 [8]
 [4]
 [0]], shape: (6, 1)
hstack:
[[2 8]
 [2 4]
 [4 0]], shape: (3, 2)


In [4]:
# Matrix and Vector
import numpy as np

a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (4, ))
c = np.random.randint(0, 10, (3,1))
print(f'a:\n{a}, shape: {a.shape}')
print(f'b:\n{b}, shape: {b.shape}')
print(f'c:\n{c}, shape: {c.shape}\n')

vstack = np.vstack([a, b])
hstack = np.hstack([a,c])
print(f'vstack:\n{vstack}, shape: {vstack.shape}')
print(f'hstack:\n{hstack}, shape: {hstack.shape}')

a:
[[8 9 1 0]
 [9 8 1 8]
 [3 0 0 5]], shape: (3, 4)
b:
[5 2 4 1], shape: (4,)
c:
[[4]
 [6]
 [2]], shape: (3, 1)

vstack:
[[8 9 1 0]
 [9 8 1 8]
 [3 0 0 5]
 [5 2 4 1]], shape: (4, 4)
hstack:
[[8 9 1 0 4]
 [9 8 1 8 6]
 [3 0 0 5 2]], shape: (3, 5)


### 1-2.Making Toy Datasets

In [5]:
# Row
import numpy as np

dataset = np.empty((0,4))
print(f'initial shape: {dataset.shape}\n')

for iter in range(5):
    sample = np.random.uniform(0, 5, (1,4))
    dataset = np.vstack([dataset, sample])
    print(f'iter/shape: {iter}/{dataset.shape}')

initial shape: (0, 4)

iter/shape: 0/(1, 4)
iter/shape: 1/(2, 4)
iter/shape: 2/(3, 4)
iter/shape: 3/(4, 4)
iter/shape: 4/(5, 4)


In [6]:
# Column
import numpy as np

dataset = np.empty((4, 0))
print(f'initial shape: {dataset.shape}\n')

for iter in range(5):
    sample = np.random.uniform(0, 5, (4, 1))
    dataset = np.hstack([dataset, sample])
    print(f'iter/shape: {iter}/{dataset.shape}')

initial shape: (4, 0)

iter/shape: 0/(4, 1)
iter/shape: 1/(4, 2)
iter/shape: 2/(4, 3)
iter/shape: 3/(4, 4)
iter/shape: 4/(4, 5)


### 1-3.Making Toy Datasets(Efficient way)

In [7]:
import numpy as np

a = np.random.randint(0, 10 ,(1, 4))
b = np.random.randint(0, 10 ,(1, 4))
c = np.random.randint(0, 10 ,(1, 4))
print(f'a:\n{a}, shape:{a.shape}')
print(f'b:\n{b}, shape:{b.shape}')
print(f'c:\n{c}, shape:{c.shape}\n')

arr_list = [a, b, c]
vstack = np.vstack(arr_list)
hstack = np.hstack(arr_list)
print(f'vstack:\n{vstack}, shape: {vstack.shape}')
print(f'hstack:\n{hstack}, shape: {hstack.shape}')

a:
[[0 3 7 5]], shape:(1, 4)
b:
[[4 9 2 3]], shape:(1, 4)
c:
[[6 5 6 4]], shape:(1, 4)

vstack:
[[0 3 7 5]
 [4 9 2 3]
 [6 5 6 4]], shape: (3, 4)
hstack:
[[0 3 7 5 4 9 2 3 6 5 6 4]], shape: (1, 12)


In [8]:
import numpy as np

dataset_tmp = []
for iter in range(100):
    sample = np.random.uniform(0, 5, (1,4))
    dataset_tmp.append(sample)

dataset = np.vstack(dataset_tmp)
print(f'dataset.shape: {dataset.shape}')

dataset.shape: (100, 4)


## 2.np.concatenate

### 2-1.Usage

In [9]:
# Vector
import numpy as np

a = np.random.randint(0, 10, (3, ))
b = np.random.randint(0, 10, (4, ))
c = np.random.randint(0, 10, (5, ))
print(f'a:\n{a}, shape: {a.shape}')
print(f'b:\n{b}, shape: {b.shape}')
print(f'c:\n{c}, shape: {c.shape}\n')

concat = np.concatenate([a, b, c])
concat0 = np.concatenate([a, b, c], axis=0)
print(f'conat:\n{concat}, shape: {concat.shape}')
print(f'conat0:\n{concat0}, shape: {concat0.shape}')

a:
[2 5 3], shape: (3,)
b:
[9 5 1 6], shape: (4,)
c:
[2 2 5 6 9], shape: (5,)

conat:
[2 5 3 9 5 1 6 2 2 5 6 9], shape: (12,)
conat0:
[2 5 3 9 5 1 6 2 2 5 6 9], shape: (12,)


In [10]:
# Row vector
import numpy as np

a = np.random.randint(0, 10, (1, 3))
b = np.random.randint(0, 10, (1, 3))
print(f'a:\n{a}, shape: {a.shape}')
print(f'b:\n{b}, shape: {b.shape}\n')

concat0 = np.concatenate([a,b], axis=0)
concat1 = np.concatenate([a,b], axis=1)
concat_n1 = np.concatenate([a,b], axis=-1)
print(f'concat0:\n{concat0}, shape:{concat0.shape}')
print(f'concat1:\n{concat1}, shape:{concat1.shape}')
print(f'concat_n1:\n{concat_n1}, shape:{concat_n1.shape}')

a:
[[3 8 5]], shape: (1, 3)
b:
[[1 0 8]], shape: (1, 3)

concat0:
[[3 8 5]
 [1 0 8]], shape:(2, 3)
concat1:
[[3 8 5 1 0 8]], shape:(1, 6)
concat_n1:
[[3 8 5 1 0 8]], shape:(1, 6)


In [11]:
# Matrix
import numpy as np

a = np.random.randint(0, 10, (3, 4))
b = np.random.randint(0, 10, (3, 2))
print(f'a:\n{a}, shape: {a.shape}')
print(f'b:\n{b}, shape: {b.shape}\n')

concat1 = np.concatenate([a,b], axis=1)
print(f'concat1:\n{concat1}, shape: {concat1.shape}')

a:
[[6 6 3 2]
 [7 3 4 1]
 [0 0 7 2]], shape: (3, 4)
b:
[[9 9]
 [9 1]
 [9 5]], shape: (3, 2)

concat1:
[[6 6 3 2 9 9]
 [7 3 4 1 9 1]
 [0 0 7 2 9 5]], shape: (3, 6)


In [12]:
# Tensor

a = np.random.randint(0, 10, (3, 4, 5))
b = np.random.randint(0, 10, (10, 4, 5))
c = np.random.randint(0, 10, (3, 10, 5))
d = np.random.randint(0, 10, (3, 4, 10))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}')
print(f'd.shape: {d.shape}\n')

concat0 = np.concatenate([a, b], axis=0)
print(f'concat0.shape: {concat0.shape}\n')

concat1 = np.concatenate([a, c], axis=1)
print(f'concat1.shape: {concat1.shape}\n')

concat2 = np.concatenate([a, d], axis=2)
print(f'concat2.shape: {concat2.shape}')

a.shape: (3, 4, 5)
b.shape: (10, 4, 5)
c.shape: (3, 10, 5)
d.shape: (3, 4, 10)

concat0.shape: (13, 4, 5)

concat1.shape: (3, 14, 5)

concat2.shape: (3, 4, 15)


## 2-2.Making Toy Datasets

In [13]:
import numpy as np

dataset_tmp = []
for iter in range(100):
    sample = np.random.uniform(0, 5, (1,4))
    dataset_tmp.append(sample)

dataset = np.concatenate(dataset_tmp, axis=0)
print(f'dataset.shape: {dataset.shape}\n')

dataset_tmp = []
for iter in range(100):
    sample = np.random.uniform(0, 5, (4,1))
    dataset_tmp.append(sample)

dataset = np.concatenate(dataset_tmp, axis=1)
print(f'dataset.shape: {dataset.shape}')

dataset.shape: (100, 4)

dataset.shape: (4, 100)


## 3.np.dstack
새로운 차원을 만들면서 합침

In [14]:
# 2차원
import numpy as np

R = np.random.randint(0, 10, (100, 200))
G = np.random.randint(0, 10, size=R.shape)
B = np.random.randint(0, 10, size=R.shape)
print(f'R.shape: {R.shape}')
print(f'G.shape: {G.shape}')
print(f'B.shape: {B.shape}\n')

image = np.dstack([R, G, B])
print(f'image.shape: {image.shape}')

R.shape: (100, 200)
G.shape: (100, 200)
B.shape: (100, 200)

image.shape: (100, 200, 3)


In [15]:
# 3차원
import numpy as np

a = np.random.randint(0, 10, (100, 200, 3))
b = np.random.randint(0, 10, size=a.shape)
c = np.random.randint(0, 10, size=a.shape)
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}\n')

d = np.dstack([a, b, c])
print(f'd.shape: {d.shape}')

a.shape: (100, 200, 3)
b.shape: (100, 200, 3)
c.shape: (100, 200, 3)

d.shape: (100, 200, 9)


## 4.np.stack

In [16]:
# 2차원
import numpy as np

a = np.random.randint(0, 10, (100, 200))
b = np.random.randint(0, 10, (100, 200))
c = np.random.randint(0, 10, (100, 200))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}\n')

stack = np.stack([a,b,c])
print(f'stack.shape : {stack.shape}')

a.shape: (100, 200)
b.shape: (100, 200)
c.shape: (100, 200)

stack.shape : (3, 100, 200)


In [17]:
# 3차원
a = np.random.randint(0, 10, (100, 200, 300))
b = np.random.randint(0, 10, (100, 200, 300))
c = np.random.randint(0, 10, (100, 200, 300))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}\n')

stack = np.stack([a, b, c])
print(f'stack.shape : {stack.shape}')

a.shape: (100, 200, 300)
b.shape: (100, 200, 300)
c.shape: (100, 200, 300)

stack.shape : (3, 100, 200, 300)


In [18]:
# axis 
a = np.random.randint(0, 10, (100, 200, 300))
b = np.random.randint(0, 10, (100, 200, 300))
c = np.random.randint(0, 10, (100, 200, 300))
print(f'a.shape: {a.shape}')
print(f'b.shape: {b.shape}')
print(f'c.shape: {c.shape}\n')

stack0 = np.stack([a, b, c], axis=0)
stack1 = np.stack([a, b, c], axis=1)
stack2 = np.stack([a, b, c], axis=2)
stack3 = np.stack([a, b, c], axis=3)
print(f'stack0.shape: {stack0.shape}')
print(f'stack1.shape: {stack1.shape}')
print(f'stack2.shape: {stack2.shape}')
print(f'stack3.shape: {stack3.shape}')

a.shape: (100, 200, 300)
b.shape: (100, 200, 300)
c.shape: (100, 200, 300)

stack0.shape: (3, 100, 200, 300)
stack1.shape: (100, 3, 200, 300)
stack2.shape: (100, 200, 3, 300)
stack3.shape: (100, 200, 300, 3)
