## 1.Fully-connected Operation of Scalar

### 1-1.with For loop

In [1]:
#method 1
import numpy as np

x = np.arange(5)
y = np.arange(2, 6)
print(f'x: {x}')
print(f'y : {y}\n')


for x_val in x:
    for y_val in y:
       print(f'{x_val} + {y_val} = {x_val + y_val},', end = ' ')
    print()

print('---------------------------------------------')

# method 2
x = np.arange(5)
y = np.arange(2, 6)
print(f'x: {x}')
print(f'y : {y}\n')

for x_val in x:
    print(f'{x_val} + {y} = {x_val + y}')

x: [0 1 2 3 4]
y : [2 3 4 5]

0 + 2 = 2, 0 + 3 = 3, 0 + 4 = 4, 0 + 5 = 5, 
1 + 2 = 3, 1 + 3 = 4, 1 + 4 = 5, 1 + 5 = 6, 
2 + 2 = 4, 2 + 3 = 5, 2 + 4 = 6, 2 + 5 = 7, 
3 + 2 = 5, 3 + 3 = 6, 3 + 4 = 7, 3 + 5 = 8, 
4 + 2 = 6, 4 + 3 = 7, 4 + 4 = 8, 4 + 5 = 9, 
---------------------------------------------
x: [0 1 2 3 4]
y : [2 3 4 5]

0 + [2 3 4 5] = [2 3 4 5]
1 + [2 3 4 5] = [3 4 5 6]
2 + [2 3 4 5] = [4 5 6 7]
3 + [2 3 4 5] = [5 6 7 8]
4 + [2 3 4 5] = [6 7 8 9]


### 1-2.with np.meshgrid

In [2]:
import numpy as np

x = np.arange(5)
y = np.arange(2, 6)
print(f'x: {x}')
print(f'y : {y}\n')

X, Y = np.meshgrid(x, y)
X, Y = X.T, Y.T
print(f'X:\n{X}')
print(f'Y:\n{Y}\n')

Z = X + Y
print(f'Z:\n{Z}')

x: [0 1 2 3 4]
y : [2 3 4 5]

X:
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
Y:
[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]

Z:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


### 1-3.with Broadcasting

In [3]:
# 두개 더할때
import numpy as np

x = np.arange(5)
y = np.arange(2, 6)
print(f'x: {x}')
print(f'y : {y}\n')

X = x.reshape((-1,1))
Y = y.reshape((1, -1))
print(f'X:\n{X}, shape: {X.shape}')
print(f'Y:\n{Y}, shape: {Y.shape}\n')

Z = X + Y
print(f'Z:\n{Z}, shape: {Z.shape}\n')

print(f'x[0] +y: {Z[0, :]}')
print(f'x[4] +y: {Z[4, :]}\n')

print(f'x +y[0]: {Z[:, 0]}')
print(f'x +y[2]: {Z[:, 2]}')

x: [0 1 2 3 4]
y : [2 3 4 5]

X:
[[0]
 [1]
 [2]
 [3]
 [4]], shape: (5, 1)
Y:
[[2 3 4 5]], shape: (1, 4)

Z:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]], shape: (5, 4)

x[0] +y: [2 3 4 5]
x[4] +y: [6 7 8 9]

x +y[0]: [2 3 4 5 6]
x +y[2]: [4 5 6 7 8]


In [4]:
# 세개 더할때
import numpy as np

x = np.arange(5)
y = np.arange(2, 6)
z = np.arange(4,7)
print(f'x: {x}, shape: {x.shape}')
print(f'y : {y}, shape: {y.shape}')
print(f'z : {z}, shape: {z.shape}\n')

x = np.expand_dims(x, axis=(1,2))
y = np.expand_dims(y, axis=(0,2))
z = np.expand_dims(z, axis=(0,1))
print(f'x:\n{x}, shape: {x.shape}')
print(f'y:\n{y}, shape: {y.shape}')
print(f'z:\n{z}, shape: {z.shape}\n')

print(f'x+y+z:\n{x+y+z}, shape: {(x+y+z).shape}')

x: [0 1 2 3 4], shape: (5,)
y : [2 3 4 5], shape: (4,)
z : [4 5 6], shape: (3,)

x:
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]], shape: (5, 1, 1)
y:
[[[2]
  [3]
  [4]
  [5]]], shape: (1, 4, 1)
z:
[[[4 5 6]]], shape: (1, 1, 3)

x+y+z:
[[[ 6  7  8]
  [ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]
  [10 11 12]]

 [[ 8  9 10]
  [ 9 10 11]
  [10 11 12]
  [11 12 13]]

 [[ 9 10 11]
  [10 11 12]
  [11 12 13]
  [12 13 14]]

 [[10 11 12]
  [11 12 13]
  [12 13 14]
  [13 14 15]]], shape: (5, 4, 3)


## 2.Fully-connected Operation of Vector

### 2-1.with For loop

In [5]:
import numpy as np

X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}\n')

for x in X:
    for y in Y:
        print((x+y).round(2), end=' ')
    print()

X:
[[-0.73  1.08]
 [ 3.38  4.79]
 [ 1.7   3.49]
 [-1.26  2.22]], shape: (4, 2)
Y:
[[ 2.01 -1.88]
 [-3.08  3.61]
 [-1.62  3.42]], shape: (3, 2)

[ 1.28 -0.8 ] [-3.81  4.69] [-2.35  4.5 ] 
[5.4  2.91] [0.31 8.4 ] [1.77 8.21] 
[3.71 1.61] [-1.38  7.1 ] [0.08 6.9 ] 
[0.75 0.34] [-4.34  5.83] [-2.88  5.63] 


### 2-2.with Broadcasting

In [6]:
# 두개 더할때
import numpy as np

X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}\n')

X = np.expand_dims(X ,axis=1)
Y = np.expand_dims(Y, axis=0)
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}\n')

Z = X + Y
print(f'Z:\n{Z.round(2)}, shape: {Z.shape}\n')

print(f'X[0] + Y:\n{Z[0, :, :].round(2)}')
print(f'X[2] + Y:\n{Z[2, :, :].round(2)}\n')

print(f'X + Y[0]:\n{Z[:, 0, :].round(2)}')
print(f'X + Y[2]:\n{Z[:, 2, :].round(2)}\n')

X:
[[-0.49  2.89]
 [-0.73 -1.89]
 [-1.89 -4.23]
 [-2.76 -2.72]], shape: (4, 2)
Y:
[[ 4.9  -1.81]
 [-0.77  1.64]
 [-3.52  2.62]], shape: (3, 2)

X:
[[[-0.49  2.89]]

 [[-0.73 -1.89]]

 [[-1.89 -4.23]]

 [[-2.76 -2.72]]], shape: (4, 1, 2)
Y:
[[[ 4.9  -1.81]
  [-0.77  1.64]
  [-3.52  2.62]]], shape: (1, 3, 2)

Z:
[[[ 4.41  1.08]
  [-1.26  4.54]
  [-4.01  5.52]]

 [[ 4.16 -3.71]
  [-1.5  -0.25]
  [-4.26  0.73]]

 [[ 3.01 -6.04]
  [-2.66 -2.59]
  [-5.41 -1.6 ]]

 [[ 2.14 -4.53]
  [-3.53 -1.07]
  [-6.28 -0.09]]], shape: (4, 3, 2)

X[0] + Y:
[[ 4.41  1.08]
 [-1.26  4.54]
 [-4.01  5.52]]
X[2] + Y:
[[ 3.01 -6.04]
 [-2.66 -2.59]
 [-5.41 -1.6 ]]

X + Y[0]:
[[ 4.41  1.08]
 [ 4.16 -3.71]
 [ 3.01 -6.04]
 [ 2.14 -4.53]]
X + Y[2]:
[[-4.01  5.52]
 [-4.26  0.73]
 [-5.41 -1.6 ]
 [-6.28 -0.09]]



In [7]:
# 세개 더할때
import numpy as np

X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))
Z = np.random.uniform(-5, 5, (2, 2))
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}')
print(f'z:\n{Z.round(2)}, shape: {Z.shape}\n')

X = np.expand_dims(X ,axis=(1, 2))
Y = np.expand_dims(Y, axis=(0, 2))
Z = np.expand_dims(Z, axis=(0, 1))
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}')
print(f'Z:\n{Z.round(2)}, shape: {Z.shape}\n')

F = X + Y + X
print(f'F:\n{F.round(2)}, shape: {F.shape}')

X:
[[-3.33  4.57]
 [ 1.13  0.93]
 [ 1.33  3.43]
 [ 1.37 -3.75]], shape: (4, 2)
Y:
[[-1.65 -0.15]
 [-2.11 -2.92]
 [-0.42  1.85]], shape: (3, 2)
z:
[[-1.31  3.92]
 [ 1.17  4.11]], shape: (2, 2)

X:
[[[[-3.33  4.57]]]


 [[[ 1.13  0.93]]]


 [[[ 1.33  3.43]]]


 [[[ 1.37 -3.75]]]], shape: (4, 1, 1, 2)
Y:
[[[[-1.65 -0.15]]

  [[-2.11 -2.92]]

  [[-0.42  1.85]]]], shape: (1, 3, 1, 2)
Z:
[[[[-1.31  3.92]
   [ 1.17  4.11]]]], shape: (1, 1, 2, 2)

F:
[[[[ -8.31   8.99]]

  [[ -8.77   6.22]]

  [[ -7.08  10.99]]]


 [[[  0.61   1.71]]

  [[  0.14  -1.05]]

  [[  1.83   3.72]]]


 [[[  1.01   6.71]]

  [[  0.55   3.95]]

  [[  2.24   8.72]]]


 [[[  1.09  -7.65]]

  [[  0.63 -10.42]]

  [[  2.32  -5.65]]]], shape: (4, 3, 1, 2)


### 2-3.Euclidean Distances

In [8]:
# x,y 좌표
import numpy as np

X = np.random.uniform(-5, 5, (4, 2))
Y = np.random.uniform(-5, 5, (3, 2))
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}\n')

# with For loop
e_distance = []
for x in X:
    e_distance_vec = []
    for y in Y:
        e_distance_vec.append(np.sqrt(np.sum(np.square(x-y))))
    e_distance.append(e_distance_vec)
e_distance = np.vstack(e_distance)

print(f'Euclidean Distance:\n{e_distance.round(2)}, shape: {e_distance.shape}')

print('-----------------------------------------------------------')       

# with Broadcasting
X = np.expand_dims(X, axis=1)
Y = np.expand_dims(Y, axis=0)
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}\n')

e_distance = np.sqrt(np.sum(np.square(X - Y), axis=-1))
print(f'Euclidean Distance:\n{e_distance.round(2)}, shape: {e_distance.shape}')

X:
[[-1.57  1.87]
 [-3.61  1.95]
 [-1.88 -4.84]
 [-3.9  -4.78]], shape: (4, 2)
Y:
[[-1.08 -4.55]
 [ 1.62  1.84]
 [-1.21  4.13]], shape: (3, 2)

Euclidean Distance:
[[6.43 3.18 2.29]
 [6.98 5.23 3.24]
 [0.85 7.54 8.99]
 [2.84 8.62 9.3 ]], shape: (4, 3)
-----------------------------------------------------------
X:
[[[-1.57  1.87]]

 [[-3.61  1.95]]

 [[-1.88 -4.84]]

 [[-3.9  -4.78]]], shape: (4, 1, 2)
Y:
[[[-1.08 -4.55]
  [ 1.62  1.84]
  [-1.21  4.13]]], shape: (1, 3, 2)

Euclidean Distance:
[[6.43 3.18 2.29]
 [6.98 5.23 3.24]
 [0.85 7.54 8.99]
 [2.84 8.62 9.3 ]], shape: (4, 3)


In [9]:
# x,y,z 좌표
import numpy as np

X = np.random.uniform(-5, 5, (4, 3))
Y = np.random.uniform(-5, 5, (3, 3))
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}\n')

e_distance = []
for x in X:
    e_distance_vec = []
    for y in Y:
        e_distance_vec.append(np.sqrt(np.sum(np.square(x-y))))
    e_distance.append(e_distance_vec)
e_distance = np.vstack(e_distance)

print(f'Euclidean Distance:\n{e_distance.round(2)}, shape: {e_distance.shape}')

print('-----------------------------------------------------------')       

# with Broadcasting
X = np.expand_dims(X, axis=1)
Y = np.expand_dims(Y, axis=0)
print(f'X:\n{X.round(2)}, shape: {X.shape}')
print(f'Y:\n{Y.round(2)}, shape: {Y.shape}\n')

e_distance = np.sqrt(np.sum(np.square(X - Y), axis=-1))
print(f'Euclidean Distance:\n{e_distance.round(2)}, shape: {e_distance.shape}')

X:
[[ 3.87  1.67  3.76]
 [ 3.24 -1.83 -2.17]
 [ 2.56 -1.04  4.51]
 [ 0.13 -4.79  4.99]], shape: (4, 3)
Y:
[[-0.23  0.84  4.93]
 [ 3.92  4.26 -0.08]
 [ 0.73  4.49  2.14]], shape: (3, 3)

Euclidean Distance:
[[ 4.34  4.63  4.52]
 [ 8.34  6.47  8.06]
 [ 3.39  7.14  6.3 ]
 [ 5.64 11.04  9.73]], shape: (4, 3)
-----------------------------------------------------------
X:
[[[ 3.87  1.67  3.76]]

 [[ 3.24 -1.83 -2.17]]

 [[ 2.56 -1.04  4.51]]

 [[ 0.13 -4.79  4.99]]], shape: (4, 1, 3)
Y:
[[[-0.23  0.84  4.93]
  [ 3.92  4.26 -0.08]
  [ 0.73  4.49  2.14]]], shape: (1, 3, 3)

Euclidean Distance:
[[ 4.34  4.63  4.52]
 [ 8.34  6.47  8.06]
 [ 3.39  7.14  6.3 ]
 [ 5.64 11.04  9.73]], shape: (4, 3)
